#!/bin/sh /etc/rc.common

START=99
STOP=01

USE_PROCD=1

PROG=/usr/bin/tailscale-derp
CONFIG_FILE=/etc/config/tailscale-derp

start_service() {
    local enabled listen stun certfile keyfile mesh mesh_key metrics health

    config_load tailscale-derp

    config_get enabled global enabled '0'
    [ "$enabled" = "1" ] || return 0

    config_get listen global listen ':3478'
    config_get stun global stun '1'
    config_get certfile tls certfile ''
    config_get keyfile tls keyfile ''
    config_get mesh mesh enabled '0'
	config_get mesh_key mesh key ''
	config_get metrics ops metrics '127.0.0.1:9911'
    config_get health ops health ':9912'

    procd_open_instance
    procd_set_param command "$PROG"
    procd_append_param command --listen "$listen"

    [ "$stun" = "1" ] && procd_append_param command --stun

    if [ -n "$certfile" ] && [ -n "$keyfile" ]; then
        procd_append_param command --certfile "$certfile"
        procd_append_param command --keyfile "$keyfile"
    fi

    if [ "$mesh" = "1" ]; then
        procd_append_param command --mesh
        [ -n "$mesh_key" ] && procd_append_param command --mesh-key "$mesh_key"
    fi

    procd_append_param command --ops "$metrics"
    procd_append_param command --health "$health"

    procd_set_param file "$CONFIG_FILE"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "tailscale-derp"
}
