#!/bin/sh /etc/rc.common

START=99
STOP=01

USE_PROCD=1

PROG=/usr/bin/tailscale-derp
CONFIG_FILE=/etc/config/tailscale-derp

start_service() {
    local enabled

    config_load tailscale-derp
    config_get enabled global enabled '1'
    [ "$enabled" = "1" ] || return 0

    procd_open_instance
    procd_set_param command "$PROG" --config "$CONFIG_FILE"

    procd_set_param file "$CONFIG_FILE"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "tailscale-derp"
}
