import { defineConfig, rspack } from "@rsbuild/core";

const luciRequires = `'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require poll';

// WARN: generated by rsbuild - do not edit
`;

export default defineConfig({
  source: {
    entry: {
      "main": "./src/views/main.tsx",
      "status": "./src/views/status.tsx",
      "peers": "./src/views/peers.tsx"
    },
    tsconfigPath: "./tsconfig.json"
  },
  resolve: {
      aliasStrategy: "prefer-tsconfig",
  },
  output: {
    module: true,
    charset: "ascii",
    overrideBrowserslist: [
      "defaults",
      "not ie <= 11",
      "not op_mini all",
      "chrome >= 60",
      "firefox >= 60",
      "safari >= 11",
      "edge >= 16"
    ],
    distPath: {
      root: "../htdocs/luci-static/resources/view/tailscale-derp",
      js: "."
    },
    filename: {
      js: "[name].js"
    },
    assetPrefix: "",
    minify: false,
    cleanDistPath: false
  },
  tools: {
    htmlPlugin: false,
    swc: {
      jsc: {
        parser: {
          syntax: "typescript",
          tsx: true,
          decorators: true,
        },
        minify: {
          compress: true,
          mangle: {},
        },
        transform: {
          react: {
            runtime: "automatic",
            importSource: "@lazulikao/luci-types",
            useBuiltins: true,
          },
          optimizer: {
            simplify: true,
          },
        },
      },
    },
    rspack: (config) => {
      config.output = config.output || {};
      config.optimization = config.optimization || {};
      config.optimization.splitChunks = false;
      config.optimization.runtimeChunk = false;
      config.optimization.minimize = false;
      config.optimization.avoidEntryIife = true;

      config.plugins = config.plugins || [];
      config.plugins.push(
        new rspack.BannerPlugin({
          banner: luciRequires,
          raw: true,
          entryOnly: true
        })
      );
      config.plugins.push(
        new rspack.BannerPlugin({
          banner: "return main;",
          raw: true,
          entryOnly: true,
          footer: true
        })
      );

      return config;
    }
  },
  performance: {
    chunkSplit: {
      strategy: "all-in-one"
    }
  }
});
