import { defineConfig, rspack } from "@rsbuild/core";

const luciRequires = `'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require poll';

// WARN: generated by rsbuild - do not edit
`;

export default defineConfig({
  source: {
    entry: {
      "tailscale-derp": "./src/views/tailscale-derp.ts",
      "tailscale-derp-status": "./src/views/tailscale-derp-status.ts"
    },
    tsconfigPath: "./tsconfig.json"
  },
  resolve: {
    alias: {
      src: "./src"
    }
  },
  output: {
    module: true,
    charset: "ascii",
    overrideBrowserslist: [
      "defaults",
      "not ie <= 11",
      "not op_mini all",
      "chrome >= 60",
      "firefox >= 60",
      "safari >= 11",
      "edge >= 16"
    ],
    distPath: {
      root: "../htdocs/luci-static/resources/view",
      js: "."
    },
    filename: {
      js: "[name].js"
    },
    assetPrefix: "",
    minify: false,
    cleanDistPath: false
  },
  tools: {
    htmlPlugin: false,
    swc: {
      jsc: {
        target: "es2020",
        parser: {
          syntax: "typescript",
          tsx: true
        },
        minify: {
          compress: true,
          mangle: {}
        },
        transform: {
          react: {
            runtime: "automatic",
            importSource: "src/utils/jsx-factory",
            development: false
          },
          optimizer: {
            simplify: true
          }
        },
        externalHelpers: true
      }
    },
    rspack: (config) => {
      config.output = config.output || {};
      config.optimization = config.optimization || {};
      config.optimization.splitChunks = false;
      config.optimization.runtimeChunk = false;
      config.optimization.minimize = false;
      config.optimization.avoidEntryIife = true;

      config.plugins = config.plugins || [];
      config.plugins.push(
        new rspack.BannerPlugin({
          banner: luciRequires,
          raw: true,
          entryOnly: true
        })
      );
      config.plugins.push(
        new rspack.BannerPlugin({
          banner: "return main;",
          raw: true,
          entryOnly: true,
          footer: true
        })
      );

      return config;
    }
  },
  performance: {
    chunkSplit: {
      strategy: "all-in-one"
    }
  }
});
