'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require poll';

// WARN: generated by rsbuild - do not edit


// UNUSED EXPORTS: main

;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = null === n || "object" != typeof n || Array.isArray(n) ? {} : n, { children: l } = s, i = _object_without_properties(s, [
        "children"
    ]), f = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o instanceof Node ? o : String(o)));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...f), e;
    }
    if ("function" == typeof o) {
        let r = Reflect.apply(o, void 0, [
            _object_spread_props(_object_spread({}, i), {
                children: f
            })
        ]);
        if (!(r instanceof Node)) throw TypeError("JSX components must return a DOM Node");
        return r;
    }
    if ("string" != typeof o) throw TypeError("JSX element types must be tag names or component functions");
    let p = {}, c = _object_spread({}, i);
    for (let [e, t] of Object.entries(c))e.startsWith("on") && "function" == typeof t ? (p[e] = t, delete c[e]) : "boolean" == typeof t && (t ? c[e] = e : delete c[e]);
    let a = Object.keys(c).length > 0 ? f.length > 1 ? E(o, c, f) : E(o, c, f[0]) : f.length > 1 ? E(o, {}, f) : E(o, {}, f[0]);
    for (let [e, t] of Object.entries(p)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./src/shared/devices.ts
let devices_e = L.rpc;
const callDevices = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "get_devices",
    reject: !0
});
const callRefreshDevices = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "refresh_devices",
    reject: !0
});
const callSetDeviceIPv4 = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "set_device_ipv4",
    params: [
        "instance",
        "device_id",
        "ipv4"
    ],
    reject: !0
});
const callSetDeviceAuthorized = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "set_device_authorized",
    params: [
        "instance",
        "device_id",
        "authorized"
    ],
    reject: !0
});
const callSetDeviceName = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "set_device_name",
    params: [
        "instance",
        "device_id",
        "name"
    ],
    reject: !0
});
const callSetDeviceTags = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "set_device_tags",
    params: [
        "instance",
        "device_id",
        "tags"
    ],
    reject: !0
});
const callSetDeviceKey = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "set_device_key",
    params: [
        "instance",
        "device_id",
        "key_expiry_disabled"
    ],
    reject: !0
});
const callDeleteDevice = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "delete_device",
    params: [
        "instance",
        "device_id"
    ],
    reject: !0
});
const callExpireDevice = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "expire_device",
    params: [
        "instance",
        "device_id"
    ],
    reject: !0
});
const callDeviceRoutes = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "get_device_routes",
    params: [
        "instance",
        "device_id"
    ],
    reject: !0
});
const callSetDeviceRoutes = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "set_device_routes",
    params: [
        "instance",
        "device_id",
        "routes"
    ],
    reject: !0
});
const callDeviceAttributes = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "get_device_attributes",
    params: [
        "instance",
        "device_id"
    ],
    reject: !0
});
const callSetDeviceAttribute = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "set_device_attribute",
    params: [
        "instance",
        "device_id",
        "key",
        "value",
        "expiry",
        "comment"
    ],
    reject: !0
});
const callDeleteDeviceAttribute = devices_e.declare({
    object: "luci.tailscale-derp",
    method: "delete_device_attribute",
    params: [
        "instance",
        "device_id",
        "key"
    ],
    reject: !0
});

;// CONCATENATED MODULE: ./src/views/devices/common.tsx

function formatTime(e) {
    if (!e) return "-";
    let t = new Date(e);
    return Number.isNaN(t.getTime()) ? e : t.toLocaleString();
}
function formatDeviceName(e) {
    return e.name || e.hostname || e.nodeId || _("Unnamed device");
}
function isIPv4(e) {
    let t = e.split(".");
    return 4 === t.length && t.every((e)=>/^\d+$/.test(e) && 255 >= Number(e));
}
function deviceIPv4(e) {
    var t;
    return (null == (t = e.addresses) ? void 0 : t.find(isIPv4)) || "";
}
function formatOptionalBoolean(e) {
    return void 0 === e ? "-" : e ? _("Yes") : _("No");
}
function detailField(n, i) {
    return jsxs("div", {
        class: "cbi-value",
        children: [
            jsx("label", {
                class: "cbi-value-title",
                children: n
            }),
            jsx("div", {
                class: "cbi-value-field",
                children: i
            })
        ]
    });
}
function splitValues(e) {
    return e.split(/[\n,]/).map((e)=>e.trim()).filter(Boolean);
}
function deviceOrigins(e) {
    return (e.origins || []).filter((e)=>e.instance && e.nodeId);
}
function formatOrigin(e) {
    return e.label || e.instance;
}
function setMessage(e, t) {
    let n = arguments.length > 2 && void 0 !== arguments[2] && arguments[2];
    e.style.color = n ? "#cf222e" : "#1a7f37", e.textContent = t;
}

;// CONCATENATED MODULE: ./src/views/devices/dialogs.tsx



let w = L.ui;
function dialogs_S(e, t) {
    return e instanceof Error ? e.message : t;
}
function C(e, t, n, i, l, c) {
    e.disabled = !0, t.textContent = _("Saving..."), t.style.color = "", n().then((e)=>{
        if (null == e ? void 0 : e.error) throw Error(e.error);
        return i.refresh();
    }).then(()=>{
        setMessage(t, l), i.notify(l), null == c || c();
    }).catch((e)=>{
        setMessage(t, dialogs_S(e, _("Device update failed.")), !0);
    }).finally(()=>{
        e.disabled = !1;
    });
}
function A(n) {
    let i = deviceOrigins(n);
    if (0 === i.length) return {
        element: jsx("p", {
            style: "color: #cf222e;",
            children: _("No API source is available for this device.")
        }),
        selected: ()=>void 0
    };
    if (1 === i.length) return {
        element: detailField(_("API Instance"), formatOrigin(i[0])),
        selected: ()=>i[0]
    };
    let l = jsx("select", {
        class: "cbi-input-select",
        children: i.map((t)=>jsx("option", {
                value: "".concat(t.instance, "\0").concat(t.nodeId),
                children: formatOrigin(t)
            }))
    });
    return {
        element: jsxs("div", {
            class: "cbi-value",
            children: [
                jsx("label", {
                    class: "cbi-value-title",
                    children: _("API Instance")
                }),
                jsx("div", {
                    class: "cbi-value-field",
                    children: l
                })
            ]
        }),
        selected: ()=>i.find((e)=>"".concat(e.instance, "\0").concat(e.nodeId) === l.value),
        select: l
    };
}
function N(e) {
    setMessage(e, _("No API source is available for this device."), !0);
}
function P(n, i, l, c, o) {
    let r;
    (r = jsx("button", {
        class: "cbi-button cbi-button-negative",
        type: "button",
        children: _("Confirm")
    })).onclick = ()=>{
        w.hideModal(), l().then((e)=>{
            if (null == e ? void 0 : e.error) throw Error(e.error);
            return c.refresh();
        }).then(()=>c.notify(o)).catch((e)=>c.notify(dialogs_S(e, _("Device update failed.")), !0));
    }, w.showModal(n, jsxs("div", {
        children: [
            jsx("p", {
                children: i
            }),
            jsxs("div", {
                style: "margin-top: 0.75em; text-align: right;",
                children: [
                    jsx("button", {
                        class: "cbi-button cbi-button-neutral",
                        type: "button",
                        onclick: w.hideModal,
                        children: _("Cancel")
                    }),
                    " ",
                    r
                ]
            })
        ]
    }));
}
function showDeviceDetails(n) {
    var i, l, c;
    let o = n.nodeKey ? jsx("code", {
        style: "word-break: break-all;",
        children: n.nodeKey
    }) : "-";
    w.showModal(_("Device Details"), jsxs("div", {
        children: [
            detailField(_("Name"), formatDeviceName(n)),
            detailField(_("Hostname"), n.hostname || "-"),
            detailField(_("User"), n.user || "-"),
            detailField(_("Node ID"), n.nodeId || "-"),
            detailField(_("Node Key"), o),
            detailField(_("Platform"), [
                n.os,
                n.clientVersion
            ].filter(Boolean).join(" / ") || "-"),
            detailField(_("Addresses"), (null == (i = n.addresses) ? void 0 : i.join(", ")) || "-"),
            detailField(_("Last Seen"), formatTime(n.lastSeen)),
            detailField(_("Key Expiry"), n.keyExpiryDisabled ? _("Disabled") : formatTime(n.expires)),
            detailField(_("Tags"), (null == (l = n.tags) ? void 0 : l.join(", ")) || "-"),
            detailField(_("Sources"), (null == (c = n.sources) ? void 0 : c.join(", ")) || "-"),
            detailField(_("Authorized"), formatOptionalBoolean(n.authorized)),
            detailField(_("Connected to Control"), formatOptionalBoolean(n.connectedToControl)),
            detailField(_("External"), formatOptionalBoolean(n.isExternal)),
            detailField(_("Ephemeral"), formatOptionalBoolean(n.isEphemeral)),
            detailField(_("Multiple Connections"), formatOptionalBoolean(n.multipleConnections)),
            jsx("div", {
                style: "margin-top: 0.75em; text-align: right;",
                children: jsx("button", {
                    class: "cbi-button cbi-button-neutral",
                    type: "button",
                    onclick: w.hideModal,
                    children: _("Close")
                })
            })
        ]
    }));
}
function showDeviceEditor(l, c) {
    let o = A(l), s = jsx("input", {
        class: "cbi-input-text",
        type: "text",
        value: l.name || ""
    }), h = jsx("input", {
        class: "cbi-input-text",
        type: "text",
        value: deviceIPv4(l),
        placeholder: "100.64.0.1"
    }), y = jsx("textarea", {
        class: "cbi-input-text",
        rows: 3
    });
    y.value = (l.tags || []).join("\n");
    let x = jsx("input", {
        type: "checkbox"
    });
    x.checked = !!l.authorized;
    let f = jsx("input", {
        type: "checkbox"
    });
    f.checked = !!l.keyExpiryDisabled;
    let g = jsx("div", {
        style: "min-height: 1.2em; margin-top: 0.75em;"
    }), k = jsx("button", {
        class: "cbi-button cbi-button-save",
        type: "button",
        children: _("Save Name")
    }), S = jsx("button", {
        class: "cbi-button cbi-button-save",
        type: "button",
        children: _("Save IPv4")
    }), M = jsx("button", {
        class: "cbi-button cbi-button-save",
        type: "button",
        children: _("Save Tags")
    }), j = jsx("button", {
        class: "cbi-button cbi-button-save",
        type: "button",
        children: _("Save Authorization")
    }), R = jsx("button", {
        class: "cbi-button cbi-button-save",
        type: "button",
        children: _("Save Key Setting")
    });
    k.onclick = ()=>{
        let e = o.selected();
        if (!e) return N(g);
        let t = s.value.trim();
        if (!t) return setMessage(g, _("Device name is required."), !0);
        C(k, g, ()=>callSetDeviceName(e.instance, e.nodeId, t), c, _("Device name updated."));
    }, S.onclick = ()=>{
        let e = o.selected(), t = h.value.trim();
        return e ? isIPv4(t) ? void C(S, g, ()=>callSetDeviceIPv4(e.instance, e.nodeId, t), c, _("Device IPv4 address updated.")) : setMessage(g, _("Enter a valid IPv4 address."), !0) : N(g);
    }, M.onclick = ()=>{
        let e = o.selected();
        if (!e) return N(g);
        C(M, g, ()=>callSetDeviceTags(e.instance, e.nodeId, splitValues(y.value)), c, _("Device tags updated."));
    }, j.onclick = ()=>{
        let e = o.selected();
        if (!e) return N(g);
        C(j, g, ()=>callSetDeviceAuthorized(e.instance, e.nodeId, x.checked), c, _("Device authorization updated."));
    }, R.onclick = ()=>{
        let e = o.selected();
        if (!e) return N(g);
        C(R, g, ()=>callSetDeviceKey(e.instance, e.nodeId, f.checked), c, _("Device key setting updated."));
    };
    let K = jsx("button", {
        class: "cbi-button cbi-button-action",
        type: "button",
        children: _("Subnet Routes")
    });
    K.onclick = ()=>showRoutesEditor(l, c);
    let z = jsx("button", {
        class: "cbi-button cbi-button-action",
        type: "button",
        children: _("Posture Attributes")
    });
    z.onclick = ()=>showAttributesEditor(l, c);
    let O = jsx("button", {
        class: "cbi-button cbi-button-negative",
        type: "button",
        children: _("Expire Key")
    });
    O.onclick = ()=>{
        let e = o.selected();
        if (!e) return N(g);
        P(_("Expire Device Key"), _("This immediately expires the device key. The device must reauthenticate to reconnect."), ()=>callExpireDevice(e.instance, e.nodeId), c, _("Device key expired."));
    };
    let T = jsx("button", {
        class: "cbi-button cbi-button-negative",
        type: "button",
        children: _("Delete Device")
    });
    T.onclick = ()=>{
        let e = o.selected();
        if (!e) return N(g);
        P(_("Delete Device"), _("This permanently removes the device from this tailnet."), ()=>callDeleteDevice(e.instance, e.nodeId), c, _("Device deleted."));
    }, w.showModal(_("Edit Device"), jsxs("div", {
        children: [
            o.element,
            detailField(_("Name"), jsxs(Fragment, {
                children: [
                    s,
                    " ",
                    k
                ]
            })),
            detailField(_("IPv4 Address"), jsxs(Fragment, {
                children: [
                    h,
                    " ",
                    S
                ]
            })),
            detailField(_("Tags"), jsxs(Fragment, {
                children: [
                    y,
                    " ",
                    M
                ]
            })),
            detailField(_("Authorized"), jsxs(Fragment, {
                children: [
                    x,
                    " ",
                    j
                ]
            })),
            detailField(_("Disable Key Expiry"), jsxs(Fragment, {
                children: [
                    f,
                    " ",
                    R
                ]
            })),
            detailField(_("Advanced"), jsxs(Fragment, {
                children: [
                    K,
                    " ",
                    z
                ]
            })),
            detailField(_("Danger Zone"), jsxs(Fragment, {
                children: [
                    O,
                    " ",
                    T
                ]
            })),
            g,
            jsx("div", {
                style: "margin-top: 0.75em; text-align: right;",
                children: jsx("button", {
                    class: "cbi-button cbi-button-neutral",
                    type: "button",
                    onclick: w.hideModal,
                    children: _("Close")
                })
            })
        ]
    }));
}
function showRoutesEditor(n, i) {
    let l = A(n), c = jsx("div", {
        children: "-"
    }), r = jsx("textarea", {
        class: "cbi-input-text",
        rows: 6,
        style: "width: 100%; box-sizing: border-box;"
    }), s = jsx("div", {
        style: "min-height: 1.2em; margin-top: 0.75em;"
    }), a = jsx("button", {
        class: "cbi-button cbi-button-save",
        type: "button",
        children: _("Save Routes")
    }), d = ()=>{
        let e = l.selected();
        if (!e) return N(s);
        s.textContent = _("Loading routes..."), callDeviceRoutes(e.instance, e.nodeId).then((e)=>{
            if (null == e ? void 0 : e.error) throw Error(e.error);
            r.value = (e.enabledRoutes || []).join("\n"), c.textContent = (e.advertisedRoutes || []).join(", ") || "-", s.textContent = "";
        }).catch((e)=>setMessage(s, dialogs_S(e, _("Unable to load routes.")), !0));
    };
    l.select && (l.select.onchange = d), a.onclick = ()=>{
        let e = l.selected();
        if (!e) return N(s);
        C(a, s, ()=>callSetDeviceRoutes(e.instance, e.nodeId, splitValues(r.value)), i, _("Device routes updated."));
    }, w.showModal(_("Subnet Routes"), jsxs("div", {
        children: [
            l.element,
            detailField(_("Advertised Routes"), c),
            detailField(_("Enabled Routes"), r),
            jsx("p", {
                children: _("Enter one CIDR route per line. Saving replaces the enabled route list.")
            }),
            s,
            jsxs("div", {
                style: "margin-top: 0.75em; text-align: right;",
                children: [
                    jsx("button", {
                        class: "cbi-button cbi-button-neutral",
                        type: "button",
                        onclick: w.hideModal,
                        children: _("Close")
                    }),
                    " ",
                    a
                ]
            })
        ]
    })), d();
}
function showAttributesEditor(n, i) {
    let o = A(n), r = jsx("tbody", {}), a = jsx("input", {
        class: "cbi-input-text",
        type: "text",
        placeholder: "com.example.attribute"
    }), d = jsx("textarea", {
        class: "cbi-input-text",
        rows: 3,
        placeholder: '{"value": true}'
    }), u = jsx("input", {
        class: "cbi-input-text",
        type: "text",
        value: new Date(Date.now() + 2592000000).toISOString()
    }), b = jsx("input", {
        class: "cbi-input-text",
        type: "text"
    }), h = jsx("div", {
        style: "min-height: 1.2em; margin-top: 0.75em;"
    }), v = jsx("button", {
        class: "cbi-button cbi-button-save",
        type: "button",
        children: _("Set Attribute")
    }), m = ()=>{
        let n = o.selected();
        if (!n) return N(h);
        h.textContent = _("Loading posture attributes..."), callDeviceAttributes(n.instance, n.nodeId).then((n)=>{
            var c, s;
            let a;
            if (null == n ? void 0 : n.error) throw Error(n.error);
            c = n.attributes || {}, s = n.expiries || {}, 0 === (a = Object.entries(c).sort((e, t)=>{
                let [n] = e, [i] = t;
                return n.localeCompare(i);
            })).length ? r.replaceChildren(jsx("tr", {
                class: "tr",
                children: jsx("td", {
                    class: "td",
                    colSpan: 4,
                    children: _("No posture attributes configured.")
                })
            })) : r.replaceChildren(...a.map((n)=>{
                let [c, r] = n, a = jsx("button", {
                    class: "cbi-button cbi-button-negative",
                    type: "button",
                    children: _("Delete")
                });
                return a.onclick = ()=>{
                    let e = o.selected();
                    if (!e) return N(h);
                    C(a, h, ()=>callDeleteDeviceAttribute(e.instance, e.nodeId, c), i, _("Posture attribute deleted."), m);
                }, jsxs("tr", {
                    class: "tr",
                    children: [
                        jsx("td", {
                            class: "td",
                            children: jsx("code", {
                                children: c
                            })
                        }),
                        jsx("td", {
                            class: "td",
                            children: jsx("code", {
                                style: "word-break: break-all;",
                                children: JSON.stringify(r)
                            })
                        }),
                        jsx("td", {
                            class: "td",
                            children: formatTime(s[c])
                        }),
                        jsx("td", {
                            class: "td",
                            children: a
                        })
                    ]
                });
            })), h.textContent = "";
        }).catch((e)=>setMessage(h, dialogs_S(e, _("Unable to load posture attributes.")), !0));
    };
    o.select && (o.select.onchange = m), v.onclick = ()=>{
        let e = o.selected(), t = a.value.trim(), n = d.value.trim(), l = u.value.trim();
        if (!e) return N(h);
        if (!t || !n || !l) return setMessage(h, _("Attribute key, JSON value, and expiry are required."), !0);
        try {
            JSON.parse(n);
        } catch (e) {
            return setMessage(h, _("Attribute value must be valid JSON."), !0);
        }
        C(v, h, ()=>callSetDeviceAttribute(e.instance, e.nodeId, t, n, l, b.value.trim()), i, _("Posture attribute updated."), m);
    }, w.showModal(_("Posture Attributes"), jsxs("div", {
        children: [
            o.element,
            jsx("div", {
                style: "overflow-x: auto;",
                children: jsxs("table", {
                    class: "table",
                    children: [
                        jsx("thead", {
                            children: jsxs("tr", {
                                class: "tr",
                                children: [
                                    jsx("th", {
                                        class: "th",
                                        children: _("Key")
                                    }),
                                    jsx("th", {
                                        class: "th",
                                        children: _("Value")
                                    }),
                                    jsx("th", {
                                        class: "th",
                                        children: _("Expiry")
                                    }),
                                    jsx("th", {
                                        class: "th",
                                        children: _("Actions")
                                    })
                                ]
                            })
                        }),
                        r
                    ]
                })
            }),
            jsx("h4", {
                children: _("Set Attribute")
            }),
            detailField(_("Key"), a),
            detailField(_("Value (JSON)"), d),
            detailField(_("Expiry (RFC3339)"), u),
            detailField(_("Comment"), b),
            h,
            jsxs("div", {
                style: "margin-top: 0.75em; text-align: right;",
                children: [
                    jsx("button", {
                        class: "cbi-button cbi-button-neutral",
                        type: "button",
                        onclick: w.hideModal,
                        children: _("Close")
                    }),
                    " ",
                    v
                ]
            })
        ]
    })), m();
}

;// CONCATENATED MODULE: ./src/views/devices/rows.tsx



function buildDeviceRows(c, i, r) {
    let d = i.trim().toLowerCase(), h = c.filter((t)=>!d || [
            t.name,
            t.hostname,
            t.user,
            t.nodeId,
            t.nodeKey,
            ...t.tags || []
        ].some((t)=>null == t ? void 0 : t.toLowerCase().includes(d)));
    return 0 === h.length ? [
        jsx("tr", {
            class: "tr",
            children: jsx("td", {
                class: "td",
                colSpan: 5,
                style: "text-align: center;",
                children: d ? _("No matching devices") : _("No devices available")
            })
        })
    ] : h.map((c)=>{
        let i = c.authorized ? _("Authorized") : _("Not authorized"), d = c.authorized ? "#1a7f37" : "#c60", h = jsx("button", {
            class: "cbi-button cbi-button-action",
            type: "button",
            children: _("Details")
        }), u = jsx("button", {
            class: "cbi-button cbi-button-save",
            type: "button",
            children: _("Manage")
        });
        return h.onclick = ()=>showDeviceDetails(c), u.onclick = ()=>showDeviceEditor(c, r), jsxs("tr", {
            class: "tr",
            children: [
                jsx("td", {
                    class: "td",
                    style: "color: ".concat(d, "; white-space: nowrap;"),
                    children: i
                }),
                jsxs("td", {
                    class: "td",
                    children: [
                        jsx("strong", {
                            children: formatDeviceName(c)
                        }),
                        c.hostname && c.hostname !== formatDeviceName(c) ? jsx("small", {
                            style: "display: block;",
                            children: c.hostname
                        }) : null,
                        c.user ? jsx("small", {
                            style: "display: block;",
                            children: c.user
                        }) : null
                    ]
                }),
                jsx("td", {
                    class: "td",
                    style: "font-family: monospace; white-space: nowrap;",
                    children: deviceIPv4(c) || "-"
                }),
                jsx("td", {
                    class: "td",
                    children: formatTime(c.lastSeen)
                }),
                jsxs("td", {
                    class: "td",
                    style: "white-space: nowrap;",
                    children: [
                        h,
                        " ",
                        u
                    ]
                })
            ]
        });
    });
}

;// CONCATENATED MODULE: ./src/views/devices.tsx




let devices_c = L.view, devices_s = L.Poll;
function devices_a(i, n) {
    var r;
    i.devices = n.devices || [], i.countEl.textContent = _("%d device(s)").format(i.devices.length), i.updatedEl.textContent = _("Last updated: %s").format(new Date().toLocaleTimeString()), i.instancesEl.replaceChildren(...0 === (r = n.instances || []).length ? [
        jsx("p", {
            children: _("No Official API instances are configured.")
        })
    ] : r.map((i)=>{
        let n = i.configured ? i.fresh ? _("Fresh") : _("Stale or not synchronized") : _("Not configured"), r = i.fresh ? "#1a7f37" : "#c60";
        return jsxs("div", {
            class: "cbi-section-node",
            style: "margin-bottom: 0.5em;",
            children: [
                jsx("strong", {
                    children: i.label || i.name || _("Unnamed instance")
                }),
                " - ",
                i.tailnet || "-",
                " - ",
                jsx("span", {
                    style: "color: ".concat(r, ";"),
                    children: n
                }),
                " - ",
                _("%d device(s)").format(i.deviceCount || 0),
                i.error ? jsx("span", {
                    style: "color: #cf222e;",
                    children: " - ".concat(i.error)
                }) : null
            ]
        });
    })), i.updateTable();
}
function devices_o(e) {
    return callDevices().then((t)=>{
        if (null == t ? void 0 : t.error) throw Error(t.error);
        devices_a(e, t || {});
    }).catch((t)=>{
        setMessage(e.messageEl, t instanceof Error ? t.message : _("Backend unavailable"), !0);
    });
}
const main = devices_c.extend({
    load: ()=>callDevices().catch(()=>({
                devices: [],
                instances: []
            })),
    render (i) {
        let c = jsx("tbody", {}), d = jsx("div", {
            style: "margin-bottom: 0.5em;"
        }), h = jsx("div", {
            style: "font-size: 0.9em; margin-bottom: 0.5em;"
        }), m = jsx("div", {
            style: "min-height: 1.2em; margin-bottom: 0.5em;"
        }), v = jsx("div", {}), f = jsx("input", {
            class: "cbi-input-text",
            type: "search",
            placeholder: _("Search devices..."),
            style: "width: 100%;"
        }), u = jsx("button", {
            class: "cbi-button cbi-button-action",
            type: "button",
            children: _("Refresh")
        }), b = {
            tableBody: c,
            countEl: d,
            updatedEl: h,
            messageEl: m,
            instancesEl: v,
            searchEl: f,
            refreshEl: u,
            devices: [],
            updateTable: ()=>void 0,
            refresh: ()=>Promise.resolve()
        }, p = {
            refresh: ()=>devices_o(b),
            notify: function(e) {
                let t = arguments.length > 1 && void 0 !== arguments[1] && arguments[1];
                return setMessage(m, e, t);
            }
        };
        return b.updateTable = ()=>c.replaceChildren(...buildDeviceRows(b.devices, f.value, p)), b.refresh = ()=>devices_o(b), f.oninput = b.updateTable, u.onclick = ()=>{
            u.disabled = !0, m.style.color = "", m.textContent = _("Refreshing Official API devices..."), callRefreshDevices().then((e)=>{
                if (null == e ? void 0 : e.error) throw Error(e.error);
                devices_a(b, e || {}), setMessage(m, _("Device data refreshed."));
            }).catch((e)=>setMessage(m, e instanceof Error ? e.message : _("Refresh failed"), !0)).finally(()=>{
                u.disabled = !1;
            });
        }, devices_a(b, i || {}), devices_s.add(()=>devices_o(b), 15), jsxs("div", {
            children: [
                jsx("h2", {
                    children: _("Tailscale Devices")
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("h3", {
                            children: _("Official API Synchronization")
                        }),
                        v,
                        h,
                        u,
                        " ",
                        m
                    ]
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("h3", {
                            children: _("Devices")
                        }),
                        d,
                        jsx("div", {
                            style: "margin-bottom: 0.75em;",
                            children: f
                        }),
                        jsx("div", {
                            style: "overflow-x: auto;",
                            children: jsxs("table", {
                                class: "table",
                                children: [
                                    jsx("thead", {
                                        children: jsxs("tr", {
                                            class: "tr",
                                            children: [
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Status")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Device")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("IPv4")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Last Seen")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Actions")
                                                })
                                            ]
                                        })
                                    }),
                                    c
                                ]
                            })
                        })
                    ]
                })
            ]
        });
    },
    handleSave: null,
    handleSaveApply: null,
    handleReset: null
});


return main;