'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require poll';

// WARN: generated by rsbuild - do not edit


// UNUSED EXPORTS: main

;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = null === n || "object" != typeof n || Array.isArray(n) ? {} : n, { children: l } = s, i = _object_without_properties(s, [
        "children"
    ]), f = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o instanceof Node ? o : String(o)));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...f), e;
    }
    if ("function" == typeof o) {
        let r = Reflect.apply(o, void 0, [
            _object_spread_props(_object_spread({}, i), {
                children: f
            })
        ]);
        if (!(r instanceof Node)) throw TypeError("JSX components must return a DOM Node");
        return r;
    }
    if ("string" != typeof o) throw TypeError("JSX element types must be tag names or component functions");
    let p = {}, c = _object_spread({}, i);
    for (let [e, t] of Object.entries(c))e.startsWith("on") && "function" == typeof t ? (p[e] = t, delete c[e]) : "boolean" == typeof t && (t ? c[e] = e : delete c[e]);
    let a = Object.keys(c).length > 0 ? f.length > 1 ? E(o, c, f) : E(o, c, f[0]) : f.length > 1 ? E(o, {}, f) : E(o, {}, f[0]);
    for (let [e, t] of Object.entries(p)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./src/views/devices.tsx

let devices_n = L.view, devices_l = L.rpc, devices_c = L.ui, devices_i = L.Poll, devices_a = devices_l.declare({
    object: "luci.tailscale-derp",
    method: "get_devices"
}), devices_s = devices_l.declare({
    object: "luci.tailscale-derp",
    method: "refresh_devices"
});
function d(e) {
    return e.name || e.hostname || e.nodeId || _("Unnamed device");
}
function devices_o(n, l) {
    var c;
    n.devices = (null == l ? void 0 : l.devices) || [], n.countEl.textContent = _("%d device(s)").format(n.devices.length), n.updatedEl.textContent = _("Last updated: %s").format(new Date().toLocaleTimeString()), n.instancesEl.replaceChildren(...0 === (c = (null == l ? void 0 : l.instances) || []).length ? [
        jsx("p", {
            children: _("No Official API instances are configured.")
        })
    ] : c.map((n)=>{
        let l = n.configured ? n.fresh ? _("Fresh") : _("Stale or not synchronized") : _("Not configured"), c = n.fresh ? "#1a7f37" : "#c60";
        return jsxs("div", {
            class: "cbi-section-node",
            style: "margin-bottom: 0.5em;",
            children: [
                jsx("strong", {
                    children: n.label || n.name || _("Unnamed instance")
                }),
                " - ",
                n.tailnet || "-",
                " - ",
                jsx("span", {
                    style: "color: ".concat(c, ";"),
                    children: l
                }),
                " - ",
                _('%d device(s)').format(n.deviceCount || 0),
                n.error ? jsx("span", {
                    style: "color: #cf222e;",
                    children: " - ".concat(n.error)
                }) : null
            ]
        });
    })), n.updateTable();
}
const main = devices_n.extend({
    load: ()=>devices_a().catch(()=>({
                devices: [],
                instances: []
            })),
    render (n) {
        let l = jsx("tbody", {}), r = jsx("div", {
            style: "margin-bottom: 0.5em;"
        }), h = jsx("div", {
            style: "font-size: 0.9em; margin-bottom: 0.5em;"
        }), u = jsx("div", {
            style: "color: #cf222e; min-height: 1.2em; margin-bottom: 0.5em;"
        }), m = jsx("div", {}), v = jsx("input", {
            class: "cbi-input-text",
            type: "search",
            placeholder: _("Search devices..."),
            style: "width: 100%;"
        }), f = jsx("button", {
            class: "cbi-button cbi-button-action",
            type: "button",
            children: _("Refresh")
        }), b = {
            tableBody: l,
            countEl: r,
            updatedEl: h,
            messageEl: u,
            instancesEl: m,
            searchEl: v,
            refreshEl: f,
            devices: [],
            updateTable: ()=>void 0
        };
        return b.updateTable = ()=>{
            let n, l;
            b.tableBody.replaceChildren(...(n = b.searchEl.value.trim().toLowerCase(), 0 === (l = b.devices.filter((e)=>!n || [
                    e.name,
                    e.hostname,
                    e.user,
                    e.nodeId,
                    e.nodeKey,
                    ...e.tags || []
                ].some((e)=>null == e ? void 0 : e.toLowerCase().includes(n)))).length ? [
                jsx("tr", {
                    class: "tr",
                    children: jsx("td", {
                        class: "td",
                        colSpan: 8,
                        style: "text-align: center;",
                        children: n ? _("No matching devices") : _("No devices available")
                    })
                })
            ] : l.map((n)=>{
                var l, i;
                let a = n.nodeKey || "-", s = n.authorized ? _("Authorized") : _("Not authorized"), o = n.authorized ? "#1a7f37" : "#c60", r = n.nodeKey ? jsx("button", {
                    class: "cbi-button cbi-button-action",
                    type: "button",
                    onclick: ()=>{
                        navigator.clipboard.writeText(n.nodeKey || "").then(()=>{
                            devices_c.addNotification(null, jsx("p", {
                                children: _("Node key copied")
                            }));
                        }).catch(()=>{
                            devices_c.addNotification(null, jsx("p", {
                                children: _("Unable to copy node key")
                            }));
                        });
                    },
                    children: _("Copy")
                }) : null;
                return jsxs("tr", {
                    class: "tr",
                    children: [
                        jsx("td", {
                            class: "td",
                            style: "color: ".concat(o, "; white-space: nowrap;"),
                            children: s
                        }),
                        jsxs("td", {
                            class: "td",
                            children: [
                                jsx("strong", {
                                    children: d(n)
                                }),
                                n.hostname && n.hostname !== d(n) ? jsx("small", {
                                    style: "display: block;",
                                    children: n.hostname
                                }) : null
                            ]
                        }),
                        jsxs("td", {
                            class: "td",
                            style: "font-family: monospace; white-space: nowrap;",
                            title: a,
                            children: [
                                function(e) {
                                    let t = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : 20;
                                    return e.length > t ? "".concat(e.substring(0, t), "...") : e;
                                }(a),
                                " ",
                                r
                            ]
                        }),
                        jsx("td", {
                            class: "td",
                            children: n.user || "-"
                        }),
                        jsx("td", {
                            class: "td",
                            children: [
                                n.os,
                                n.clientVersion
                            ].filter(Boolean).join(" / ") || "-"
                        }),
                        jsx("td", {
                            class: "td",
                            children: (null == (l = n.addresses) ? void 0 : l.join(", ")) || "-"
                        }),
                        jsx("td", {
                            class: "td",
                            children: function(e) {
                                if (!e) return "-";
                                let t = new Date(e);
                                return Number.isNaN(t.getTime()) ? e : t.toLocaleString();
                            }(n.lastSeen)
                        }),
                        jsx("td", {
                            class: "td",
                            children: (null == (i = n.sources) ? void 0 : i.join(", ")) || "-"
                        })
                    ]
                });
            })));
        }, v.oninput = b.updateTable, f.onclick = ()=>{
            f.disabled = !0, u.style.color = "", u.textContent = _("Refreshing Official API devices..."), devices_s().then((e)=>{
                u.style.color = "#1a7f37", u.textContent = _("Device data refreshed."), devices_o(b, e || {});
            }).catch((e)=>{
                u.style.color = "#cf222e", u.textContent = e instanceof Error ? e.message : _("Refresh failed");
            }).finally(()=>{
                f.disabled = !1;
            });
        }, devices_o(b, n || {}), devices_i.add(()=>devices_a().then((e)=>{
                b.messageEl.textContent = "", devices_o(b, e || {});
            }).catch((e)=>{
                b.messageEl.textContent = e instanceof Error ? e.message : _("Backend unavailable");
            }), 15), jsxs("div", {
            children: [
                jsx("h2", {
                    children: _("Tailscale Devices")
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("h3", {
                            children: _("Official API Synchronization")
                        }),
                        m,
                        h,
                        f,
                        " ",
                        u
                    ]
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("h3", {
                            children: _("Devices")
                        }),
                        r,
                        jsx("div", {
                            style: "margin-bottom: 0.75em;",
                            children: v
                        }),
                        jsx("div", {
                            style: "overflow-x: auto;",
                            children: jsxs("table", {
                                class: "table",
                                children: [
                                    jsx("thead", {
                                        children: jsxs("tr", {
                                            class: "tr",
                                            children: [
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Status")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Device")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Node Key")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("User")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Platform")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Addresses")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Last Seen")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Sources")
                                                })
                                            ]
                                        })
                                    }),
                                    l
                                ]
                            })
                        })
                    ]
                })
            ]
        });
    },
    handleSave: null,
    handleSaveApply: null,
    handleReset: null
});


return main;