'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require poll';

// WARN: generated by rsbuild - do not edit


// UNUSED EXPORTS: main

;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = null === n || "object" != typeof n || Array.isArray(n) ? {} : n, { children: l } = s, i = _object_without_properties(s, [
        "children"
    ]), f = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o instanceof Node ? o : String(o)));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...f), e;
    }
    if ("function" == typeof o) {
        let r = Reflect.apply(o, void 0, [
            _object_spread_props(_object_spread({}, i), {
                children: f
            })
        ]);
        if (!(r instanceof Node)) throw TypeError("JSX components must return a DOM Node");
        return r;
    }
    if ("string" != typeof o) throw TypeError("JSX element types must be tag names or component functions");
    let p = {}, c = _object_spread({}, i);
    for (let [e, t] of Object.entries(c))e.startsWith("on") && "function" == typeof t ? (p[e] = t, delete c[e]) : "boolean" == typeof t && (t ? c[e] = e : delete c[e]);
    let a = Object.keys(c).length > 0 ? f.length > 1 ? E(o, c, f) : E(o, c, f[0]) : f.length > 1 ? E(o, {}, f) : E(o, {}, f[0]);
    for (let [e, t] of Object.entries(p)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./src/shared/tailnets.ts
let tailnets_e = L.rpc;
const callTailnets = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "get_tailnets",
    reject: !0
});
const callTailnetACL = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "get_tailnet_acl",
    params: [
        "instance"
    ],
    reject: !0
});
const callSetDeviceIPv4 = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "set_device_ipv4",
    params: [
        "instance",
        "device_id",
        "ipv4"
    ],
    reject: !0
});
const callValidateTailnetACL = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "validate_tailnet_acl",
    params: [
        "instance",
        "hujson"
    ],
    reject: !0
});
const callSetTailnetACL = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "set_tailnet_acl",
    params: [
        "instance",
        "hujson",
        "etag"
    ],
    reject: !0
});

;// CONCATENATED MODULE: ./src/views/devices.tsx


let devices_a = L.view, devices_c = L.rpc, devices_s = L.ui, devices_r = L.Poll, devices_o = devices_c.declare({
    object: "luci.tailscale-derp",
    method: "get_devices"
}), devices_d = devices_c.declare({
    object: "luci.tailscale-derp",
    method: "refresh_devices"
});
function h(e) {
    if (!e) return "-";
    let t = new Date(e);
    return Number.isNaN(t.getTime()) ? e : t.toLocaleString();
}
function u(e) {
    return e.name || e.hostname || e.nodeId || _("Unnamed device");
}
function v(e) {
    let t = e.split(".");
    return 4 === t.length && t.every((e)=>/^\d+$/.test(e) && 255 >= Number(e));
}
function b(e) {
    var t;
    return (null == (t = e.addresses) ? void 0 : t.find(v)) || "";
}
function m(e) {
    return void 0 === e ? "-" : e ? _("Yes") : _("No");
}
function devices_p(n, l) {
    return jsxs("div", {
        class: "cbi-value",
        children: [
            jsx("label", {
                class: "cbi-value-title",
                children: n
            }),
            jsx("div", {
                class: "cbi-value-field",
                children: l
            })
        ]
    });
}
function devices_f(n, l) {
    var i;
    n.devices = (null == l ? void 0 : l.devices) || [], n.countEl.textContent = _("%d device(s)").format(n.devices.length), n.updatedEl.textContent = _("Last updated: %s").format(new Date().toLocaleTimeString()), n.instancesEl.replaceChildren(...0 === (i = (null == l ? void 0 : l.instances) || []).length ? [
        jsx("p", {
            children: _("No Official API instances are configured.")
        })
    ] : i.map((n)=>{
        let l = n.configured ? n.fresh ? _("Fresh") : _("Stale or not synchronized") : _("Not configured"), i = n.fresh ? "#1a7f37" : "#c60";
        return jsxs("div", {
            class: "cbi-section-node",
            style: "margin-bottom: 0.5em;",
            children: [
                jsx("strong", {
                    children: n.label || n.name || _("Unnamed instance")
                }),
                " - ",
                n.tailnet || "-",
                " - ",
                jsx("span", {
                    style: "color: ".concat(i, ";"),
                    children: l
                }),
                " - ",
                _("%d device(s)").format(n.deviceCount || 0),
                n.error ? jsx("span", {
                    style: "color: #cf222e;",
                    children: " - ".concat(n.error)
                }) : null
            ]
        });
    })), n.updateTable();
}
const main = devices_a.extend({
    load: ()=>Promise.all([
            devices_o().catch(()=>({
                    devices: [],
                    instances: []
                })),
            callTailnets().catch(()=>({
                    instances: []
                }))
        ]),
    render (i) {
        let a, c = jsx("tbody", {}), y = jsx("div", {
            style: "margin-bottom: 0.5em;"
        }), g = jsx("div", {
            style: "font-size: 0.9em; margin-bottom: 0.5em;"
        }), x = jsx("div", {
            style: "color: #cf222e; min-height: 1.2em; margin-bottom: 0.5em;"
        }), I = jsx("div", {}), C = jsx("input", {
            class: "cbi-input-text",
            type: "search",
            placeholder: _("Search devices..."),
            style: "width: 100%;"
        }), E = jsx("select", {
            class: "cbi-input-select",
            style: "min-width: 18em;"
        }), w = jsx("button", {
            class: "cbi-button cbi-button-action",
            type: "button",
            children: _("Refresh")
        }), S = {
            tableBody: c,
            countEl: y,
            updatedEl: g,
            messageEl: x,
            instancesEl: I,
            searchEl: C,
            tailnetSelect: E,
            refreshEl: w,
            devices: [],
            tailnets: [],
            selectedInstance: "",
            updateTable: ()=>void 0
        };
        return S.updateTable = ()=>{
            let i, a;
            S.tableBody.replaceChildren(...(i = S.searchEl.value.trim().toLowerCase(), 0 === (a = S.devices.filter((e)=>!i || [
                    e.name,
                    e.hostname,
                    e.user,
                    e.nodeId,
                    e.nodeKey,
                    ...e.tags || []
                ].some((e)=>null == e ? void 0 : e.toLowerCase().includes(i)))).length ? [
                jsx("tr", {
                    class: "tr",
                    children: jsx("td", {
                        class: "td",
                        colSpan: 5,
                        style: "text-align: center;",
                        children: i ? _("No matching devices") : _("No devices available")
                    })
                })
            ] : a.map((i)=>{
                let a = i.authorized ? _("Authorized") : _("Not authorized"), c = i.authorized ? "#1a7f37" : "#c60", r = jsx("button", {
                    class: "cbi-button cbi-button-action",
                    type: "button",
                    children: _("Details")
                }), d = jsx("button", {
                    class: "cbi-button cbi-button-save",
                    type: "button",
                    children: _("Edit")
                });
                return r.onclick = ()=>{
                    var l, a, c;
                    let r;
                    return r = i.nodeKey ? jsxs("div", {
                        children: [
                            jsx("code", {
                                style: "word-break: break-all;",
                                children: i.nodeKey
                            }),
                            " "
                        ]
                    }) : "-", void devices_s.showModal(_("Device Details"), jsxs(Fragment, {
                        children: [
                            jsxs("div", {
                                children: [
                                    devices_p(_("Name"), u(i)),
                                    devices_p(_("Hostname"), i.hostname || "-"),
                                    devices_p(_("User"), i.user || "-"),
                                    devices_p(_("Node ID"), i.nodeId || "-"),
                                    devices_p(_("Node Key"), r),
                                    devices_p(_("Platform"), [
                                        i.os,
                                        i.clientVersion
                                    ].filter(Boolean).join(" / ") || "-"),
                                    devices_p(_("Addresses"), (null == (l = i.addresses) ? void 0 : l.join(", ")) || "-"),
                                    devices_p(_("Last Seen"), h(i.lastSeen)),
                                    devices_p(_("Key Expiry"), h(i.expires)),
                                    devices_p(_("Tags"), (null == (a = i.tags) ? void 0 : a.join(", ")) || "-"),
                                    devices_p(_("Sources"), (null == (c = i.sources) ? void 0 : c.join(", ")) || "-"),
                                    devices_p(_("Authorized"), m(i.authorized)),
                                    devices_p(_("Connected to Control"), m(i.connectedToControl)),
                                    devices_p(_("External"), m(i.isExternal)),
                                    devices_p(_("Ephemeral"), m(i.isEphemeral)),
                                    devices_p(_("Multiple Connections"), m(i.multipleConnections))
                                ]
                            }),
                            " ",
                            jsx("div", {
                                style: "margin-top: 0.75em; text-align: right;",
                                children: jsx("button", {
                                    class: "cbi-button cbi-button-neutral",
                                    type: "button",
                                    onclick: devices_s.hideModal,
                                    children: _("Close")
                                })
                            })
                        ]
                    }));
                }, d.disabled = !i.nodeId, d.onclick = ()=>{
                    let n, a, c;
                    return n = jsx("input", {
                        class: "cbi-input-text",
                        type: "text",
                        value: b(i),
                        placeholder: "100.64.0.1",
                        style: "width: 100%; box-sizing: border-box;"
                    }), a = jsx("div", {
                        style: "min-height: 1.2em; margin-top: 0.75em;"
                    }), void ((c = jsx("button", {
                        class: "cbi-button cbi-button-save",
                        type: "button",
                        children: _("Save")
                    })).disabled = !i.nodeId, c.onclick = ()=>(function(e, t, n, i, a, c) {
                            let s = e.selectedInstance, r = n.value.trim();
                            if (!s) {
                                a.style.color = "#cf222e", a.textContent = _("Select an API instance before changing an address.");
                                return;
                            }
                            if (!t.nodeId || !v(r)) {
                                a.style.color = "#cf222e", a.textContent = _("Enter a valid IPv4 address.");
                                return;
                            }
                            i.disabled = !0, a.style.color = "", a.textContent = _("Updating device IPv4 address..."), callSetDeviceIPv4(s, t.nodeId, r).then((e)=>{
                                if (null == e ? void 0 : e.error) throw Error(e.error);
                                return devices_o();
                            }).then((t)=>{
                                devices_f(e, t || {}), e.messageEl.style.color = "#1a7f37", e.messageEl.textContent = _("Device IPv4 address updated."), c();
                            }).catch((e)=>{
                                a.style.color = "#cf222e", a.textContent = e instanceof Error ? e.message : _("Unable to update device IPv4 address.");
                            }).finally(()=>{
                                i.disabled = !1;
                            });
                        })(S, i, n, c, a, devices_s.hideModal), devices_s.showModal(_("Edit Device"), jsxs("div", {
                        children: [
                            jsx("p", {
                                children: _("Change the IPv4 address for this device through the selected API instance.")
                            }),
                            devices_p(_("Device"), u(i)),
                            jsxs("div", {
                                class: "cbi-value",
                                children: [
                                    jsx("label", {
                                        class: "cbi-value-title",
                                        children: _("IPv4 Address")
                                    }),
                                    jsx("div", {
                                        class: "cbi-value-field",
                                        children: n
                                    })
                                ]
                            }),
                            a,
                            jsxs("div", {
                                style: "margin-top: 0.75em; text-align: right;",
                                children: [
                                    jsx("button", {
                                        class: "cbi-button cbi-button-neutral",
                                        type: "button",
                                        onclick: devices_s.hideModal,
                                        children: _("Cancel")
                                    }),
                                    " ",
                                    c
                                ]
                            })
                        ]
                    })));
                }, jsxs("tr", {
                    class: "tr",
                    children: [
                        jsx("td", {
                            class: "td",
                            style: "color: ".concat(c, "; white-space: nowrap;"),
                            children: a
                        }),
                        jsxs("td", {
                            class: "td",
                            children: [
                                jsx("strong", {
                                    children: u(i)
                                }),
                                i.hostname && i.hostname !== u(i) ? jsx("small", {
                                    style: "display: block;",
                                    children: i.hostname
                                }) : null,
                                i.user ? jsx("small", {
                                    style: "display: block;",
                                    children: i.user
                                }) : null
                            ]
                        }),
                        jsx("td", {
                            class: "td",
                            style: "font-family: monospace; white-space: nowrap;",
                            children: b(i) || "-"
                        }),
                        jsx("td", {
                            class: "td",
                            children: h(i.lastSeen)
                        }),
                        jsxs("td", {
                            class: "td",
                            style: "white-space: nowrap;",
                            children: [
                                r,
                                " ",
                                d
                            ]
                        })
                    ]
                });
            })));
        }, C.oninput = S.updateTable, E.onchange = ()=>{
            S.selectedInstance = E.value, S.updateTable();
        }, w.onclick = ()=>{
            w.disabled = !0, x.style.color = "", x.textContent = _("Refreshing Official API devices..."), devices_d().then((e)=>{
                if (null == e ? void 0 : e.error) throw Error(e.error);
                x.style.color = "#1a7f37", x.textContent = _("Device data refreshed."), devices_f(S, e || {});
            }).catch((e)=>{
                x.style.color = "#cf222e", x.textContent = e instanceof Error ? e.message : _("Refresh failed");
            }).finally(()=>{
                w.disabled = !1;
            });
        }, S.tailnets = ((i[1] || {}).instances || []).filter((e)=>e.configured && e.name), a = S.selectedInstance, S.tailnetSelect.replaceChildren(jsx("option", {
            value: "",
            children: _("Select an API instance")
        }), ...S.tailnets.map((t)=>jsx("option", {
                value: t.name || "",
                children: t.label || t.name
            }))), S.tailnetSelect.value = S.tailnets.some((e)=>e.name === a) ? a : "", S.selectedInstance = S.tailnetSelect.value, S.updateTable(), devices_f(S, i[0] || {}), devices_r.add(()=>devices_o().then((e)=>{
                if (null == e ? void 0 : e.error) throw Error(e.error);
                S.messageEl.textContent = "", devices_f(S, e || {});
            }).catch((e)=>{
                S.messageEl.textContent = e instanceof Error ? e.message : _("Backend unavailable");
            }), 15), jsxs("div", {
            children: [
                jsx("h2", {
                    children: _("Tailscale Devices")
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("h3", {
                            children: _("Official API Synchronization")
                        }),
                        I,
                        g,
                        jsxs("div", {
                            style: "margin-bottom: 0.75em;",
                            children: [
                                jsx("label", {
                                    children: _("API instance for device edits")
                                }),
                                jsx("br", {}),
                                E
                            ]
                        }),
                        w,
                        " ",
                        x
                    ]
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("h3", {
                            children: _("Devices")
                        }),
                        y,
                        jsx("div", {
                            style: "margin-bottom: 0.75em;",
                            children: C
                        }),
                        jsx("div", {
                            style: "overflow-x: auto;",
                            children: jsxs("table", {
                                class: "table",
                                children: [
                                    jsx("thead", {
                                        children: jsxs("tr", {
                                            class: "tr",
                                            children: [
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Status")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Device")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("IPv4")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Last Seen")
                                                }),
                                                jsx("th", {
                                                    class: "th",
                                                    children: _("Actions")
                                                })
                                            ]
                                        })
                                    }),
                                    c
                                ]
                            })
                        })
                    ]
                })
            ]
        });
    },
    handleSave: null,
    handleSaveApply: null,
    handleReset: null
});


return main;