'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require tools.widgets as widgets';
'require poll';

// WARN: generated by rsbuild - do not edit


// UNUSED EXPORTS: main

;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = null === n || "object" != typeof n || Array.isArray(n) ? {} : n, { children: l } = s, i = _object_without_properties(s, [
        "children"
    ]), f = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o instanceof Node ? o : String(o)));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...f), e;
    }
    if ("function" == typeof o) {
        let r = Reflect.apply(o, void 0, [
            _object_spread_props(_object_spread({}, i), {
                children: f
            })
        ]);
        if (!(r instanceof Node)) throw TypeError("JSX components must return a DOM Node");
        return r;
    }
    if ("string" != typeof o) throw TypeError("JSX element types must be tag names or component functions");
    let p = {}, c = _object_spread({}, i);
    for (let [e, t] of Object.entries(c))e.startsWith("on") && "function" == typeof t ? (p[e] = t, delete c[e]) : "boolean" == typeof t && (t ? c[e] = e : delete c[e]);
    let a = Object.keys(c).length > 0 ? f.length > 1 ? E(o, c, f) : E(o, c, f[0]) : f.length > 1 ? E(o, {}, f) : E(o, {}, f[0]);
    for (let [e, t] of Object.entries(p)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./src/shared/sections.ts
function ensureNamedSections(e, t, o) {
    for (let [f, n, r] of o)if (!e.get(t, f)) for (let [o, i] of (e.add(t, n, f), Object.entries(null != r ? r : {})))e.set(t, f, o, i);
}

;// CONCATENATED MODULE: ./src/views/external.tsx


let external_a = L.view, external_l = L.form, external_n = L.rpc, external_i = L.uci, external_d = L.ui, external_r = external_n.declare({
    object: "luci.tailscale-derp",
    method: "reload_config"
});
function external_s(e, t, a) {
    let l = e.map.lookupOption(t, a);
    return null == l ? void 0 : l[0].formvalue(l[1]);
}
function external_o(e, t, a) {
    var l;
    let n;
    if ("manual" !== String(null != (l = external_s(this, "mode", "tls")) ? l : "self_signed")) return !0;
    let i = (n = this.section.formvalue(e, a) || "", (!t || !!n) && (!!t || !n) || _("Certificate and key must be provided together"));
    if (!0 !== i) return i;
    let d = external_s(this, "enabled", "external");
    return !!("1" !== d && !0 !== d || t.trim()) || _("Certificate and key are required when the external endpoint is enabled");
}
function external_p(e, t) {
    var a, l, n;
    if ("1" !== t && !0 !== t) return !0;
    let i = String(null != (a = external_s(this, "certfile", "tls")) ? a : "").trim(), d = String(null != (l = external_s(this, "keyfile", "tls")) ? l : "").trim();
    return "self_signed" === String(null != (n = external_s(this, "mode", "tls")) ? n : "self_signed") || !!i && !!d || _("Configure automatic TLS or provide both a certificate and key before enabling the external endpoint");
}
function u(e, t) {
    let a = String(null != t ? t : "").trim().toLowerCase();
    if ("auto" === a) return !0;
    let l = Number(a);
    return !!Number.isInteger(l) && l >= 1 && l <= 65535 || _("Port must be auto or an integer from 1 to 65535");
}
const main = external_a.extend({
    load: ()=>external_i.load("tailscale-derp").then(()=>{
            ensureNamedSections(external_i, "tailscale-derp", [
                [
                    "tls",
                    "tls",
                    {
                        mode: "self_signed",
                        state_dir: "/etc/tailscale-derp/tls"
                    }
                ],
                [
                    "external",
                    "external",
                    {
                        enabled: "0",
                        mode: "direct",
                        address_family: "ipv4",
                        method: [
                            "pcp",
                            "natpmp",
                            "upnp"
                        ],
                        wan_interface: "auto",
                        derp_port: "auto",
                        stun_port: "auto",
                        lease_seconds: "7200",
                        retry_seconds: "60",
                        sync_interval: "300",
                        validate_endpoint: "0"
                    }
                ]
            ]);
        }),
    handleSaveApply (t, a) {
        return this.super("handleSaveApply", [
            t,
            a
        ]).then(()=>external_r()).then(()=>{
            window.location.href = "/cgi-bin/luci/admin/services/derp/status";
        }).catch((t)=>{
            let a = t instanceof Error ? t.message : "unknown error";
            throw external_d.addNotification(null, jsxs("p", {
                children: [
                    _("Failed to reload DERP configuration:"),
                    " ",
                    a
                ]
            })), t;
        });
    },
    render () {
        let e = new external_l.Map("tailscale-derp", _("External Endpoint"), _("Publish this DERP relay through a WAN gateway. Tailscale does not officially support custom DERP servers behind NAT.")), t = e.section(external_l.NamedSection, "tls", "tls", _("TLS Settings")), a = t.option(external_l.ListValue, "mode", _("TLS Mode"), _("Automatic TLS generates and persists a self-signed certificate. The published DERP map pins its certificate hash."));
        return a.value("self_signed", _("Automatic Self-Signed")), a.value("manual", _("Manual Certificate Files")), a.default = "self_signed", a.rmempty = !1, (a = t.option(external_l.Value, "state_dir", _("Certificate State Directory"), _("Persistent directory for the automatic TLS private key and certificate"))).placeholder = "/etc/tailscale-derp/tls", a.default = "/etc/tailscale-derp/tls", a.rmempty = !1, a.depends("mode", "self_signed"), (a = t.option(external_l.Value, "certfile", _("Certificate File"), _("Path to the TLS certificate"))).placeholder = "/etc/ssl/certs/derp.pem", a.rmempty = !0, a.validate = function(e, t) {
            return external_o.call(this, e, t, "keyfile");
        }, a.depends("mode", "manual"), (a = t.option(external_l.Value, "keyfile", _("Key File"), _("Path to the TLS private key"))).placeholder = "/etc/ssl/private/derp.key", a.rmempty = !0, a.validate = function(e, t) {
            return external_o.call(this, e, t, "certfile");
        }, a.depends("mode", "manual"), (a = (t = e.section(external_l.NamedSection, "external", "external", _("External Endpoint (Experimental)"), _("Publish a public endpoint into selected Tailnet policies. IPv4 can use Direct or router NAT mapping; IPv6 is always published directly."))).option(external_l.Flag, "enabled", _("Enable External Endpoint"), _("Allow selected API instances to publish this relay endpoint"))).default = "0", a.rmempty = !1, a.validate = external_p, (a = t.option(external_l.ListValue, "address_family", _("Address Family"), _("IPv6 requires a globally routable address and a WAN firewall rule. In dual-stack mode, IPv4 may use Direct or NAT mapping while IPv6 remains Direct. A wildcard IPv6 listener serves IPv4 only when net.ipv6.bindv6only is 0."))).value("ipv4", _("IPv4 only")), a.value("ipv6", _("IPv6 only (Direct)")), a.value("dual", _("IPv4 + IPv6")), a.default = "ipv4", a.rmempty = !1, a.depends("enabled", "1"), (a = t.option(external_l.ListValue, "mode", _("IPv4 Exposure Mode"), _("Direct uses a public IPv4 address assigned to this router. NAT mapping asks the upstream gateway to forward IPv4 ports. IPv6 is always Direct."))).value("direct", _("Direct IPv4")), a.value("nat", _("IPv4 NAT Mapping")), a.default = "direct", a.rmempty = !1, a.depends({
            enabled: "1",
            address_family: "ipv4"
        }), a.depends({
            enabled: "1",
            address_family: "dual"
        }), (a = t.option(widgets.DeviceSelect, "wan_interface", _("Public Interface"), _("Choose auto to follow the route for each enabled address family, or select the device holding the public address."))).value("auto", _("Automatic (default route)")), a.default = "auto", a.noaliases = !0, a.nocreate = !0, a.rmempty = !1, a.depends("enabled", "1"), (a = t.option(external_l.DynamicList, "method", _("Mapping Methods"), _("Methods are attempted in this order"))).value("pcp", "PCP"), a.value("natpmp", "NAT-PMP"), a.value("upnp", "UPnP IGD"), a.default = [
            "pcp",
            "natpmp",
            "upnp"
        ], a.rmempty = !1, a.depends({
            enabled: "1",
            mode: "nat",
            address_family: "ipv4"
        }), a.depends({
            enabled: "1",
            mode: "nat",
            address_family: "dual"
        }), (a = t.option(external_l.Value, "derp_port", _("External DERP Port"), _("auto reads the actual local TCP listener and requests the same public port; the gateway may assign another port"))).default = "auto", a.rmempty = !1, a.validate = u, a.depends({
            enabled: "1",
            mode: "nat",
            address_family: "ipv4"
        }), a.depends({
            enabled: "1",
            mode: "nat",
            address_family: "dual"
        }), (a = t.option(external_l.Value, "stun_port", _("External STUN Port"), _("auto reads the actual local UDP listener and requests the same public port; the gateway may assign another port"))).default = "auto", a.rmempty = !1, a.validate = u, a.depends({
            enabled: "1",
            mode: "nat",
            address_family: "ipv4"
        }), a.depends({
            enabled: "1",
            mode: "nat",
            address_family: "dual"
        }), (a = t.option(external_l.Value, "lease_seconds", _("Mapping Lease (seconds)"))).default = "7200", a.rmempty = !1, a.datatype = "uinteger", a.depends({
            enabled: "1",
            mode: "nat",
            address_family: "ipv4"
        }), a.depends({
            enabled: "1",
            mode: "nat",
            address_family: "dual"
        }), (a = t.option(external_l.Value, "retry_seconds", _("Retry Interval (seconds)"))).default = "60", a.rmempty = !1, a.datatype = "uinteger", a.depends({
            enabled: "1",
            mode: "nat",
            address_family: "ipv4"
        }), a.depends({
            enabled: "1",
            mode: "nat",
            address_family: "dual"
        }), (a = t.option(external_l.Value, "sync_interval", _("DERP Map Sync Interval (seconds)"))).default = "300", a.rmempty = !1, a.datatype = "uinteger", a.depends("enabled", "1"), (a = t.option(external_l.Flag, "validate_endpoint", _("Validate Endpoint Locally"), _("Require a local DERP/TLS and STUN check before publishing. This does not prove Internet reachability. IPv4 and IPv6 are checked independently."))).default = "0", a.rmempty = !1, a.depends("enabled", "1"), e.render();
    }
});


return main;