'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require poll';

// WARN: generated by rsbuild - do not edit


// UNUSED EXPORTS: main

;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = null === n || "object" != typeof n || Array.isArray(n) ? {} : n, { children: l } = s, i = _object_without_properties(s, [
        "children"
    ]), f = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o instanceof Node ? o : String(o)));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...f), e;
    }
    if ("function" == typeof o) {
        let r = Reflect.apply(o, void 0, [
            _object_spread_props(_object_spread({}, i), {
                children: f
            })
        ]);
        if (!(r instanceof Node)) throw TypeError("JSX components must return a DOM Node");
        return r;
    }
    if ("string" != typeof o) throw TypeError("JSX element types must be tag names or component functions");
    let p = {}, c = _object_spread({}, i);
    for (let [e, t] of Object.entries(c))e.startsWith("on") && "function" == typeof t ? (p[e] = t, delete c[e]) : "boolean" == typeof t && (t ? c[e] = e : delete c[e]);
    let a = Object.keys(c).length > 0 ? f.length > 1 ? E(o, c, f) : E(o, c, f[0]) : f.length > 1 ? E(o, {}, f) : E(o, {}, f[0]);
    for (let [e, t] of Object.entries(p)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./src/shared/sections.ts
function ensureNamedSections(e, o, t) {
    for (let [n, d] of t)e.get(o, n) || e.add(o, d, n);
}

;// CONCATENATED MODULE: ./src/views/external.tsx


let external_a = L.view, external_n = L.form, external_r = L.rpc, external_l = L.uci, external_i = L.ui, external_o = external_r.declare({
    object: "luci.tailscale-derp",
    method: "reload_config"
});
function external_d(e, t, a) {
    let n = e.map.lookupOption(t, a);
    return null == n ? void 0 : n[0].formvalue(n[1]);
}
function external_p(e, t, a) {
    let n, r = (n = this.section.formvalue(e, a) || "", (!t || !!n) && (!!t || !n) || _("Certificate and key must be provided together"));
    if (!0 !== r) return r;
    let l = external_d(this, "enabled", "external");
    return "1" !== l && !0 !== l || !!t.trim() || _("Certificate and key are required when the external endpoint is enabled");
}
function external_s(e, t) {
    var a, n;
    if ("1" !== t && !0 !== t) return !0;
    let r = String(null != (a = external_d(this, "certfile", "tls")) ? a : "").trim(), l = String(null != (n = external_d(this, "keyfile", "tls")) ? n : "").trim();
    return !!r && !!l || _("Configure the TLS certificate and key before enabling the external endpoint");
}
function u(e, t) {
    let a = String(null != t ? t : "").trim().toLowerCase();
    if ("auto" === a) return !0;
    let n = Number(a);
    return !!Number.isInteger(n) && n >= 1 && n <= 65535 || _("Port must be auto or an integer from 1 to 65535");
}
const main = external_a.extend({
    load: ()=>external_l.load("tailscale-derp").then(()=>{
            ensureNamedSections(external_l, "tailscale-derp", [
                [
                    "tls",
                    "tls"
                ],
                [
                    "external",
                    "external"
                ]
            ]);
        }),
    handleSaveApply (t, a) {
        return this.super("handleSaveApply", [
            t,
            a
        ]).then(()=>external_o()).then(()=>{
            window.location.href = "/cgi-bin/luci/admin/services/derp/status";
        }).catch((t)=>{
            let a = t instanceof Error ? t.message : "unknown error";
            throw external_i.addNotification(null, jsxs("p", {
                children: [
                    _("Failed to reload DERP configuration:"),
                    " ",
                    a
                ]
            })), t;
        });
    },
    render () {
        let e = new external_n.Map("tailscale-derp", _("External Endpoint"), _("Publish this DERP relay through a WAN gateway. Tailscale does not officially support custom DERP servers behind NAT.")), t = e.section(external_n.NamedSection, "tls", "tls", _("TLS Settings")), a = t.option(external_n.Value, "certfile", _("Certificate File"), _("Path to TLS certificate (leave empty for auto)"));
        return a.placeholder = "/etc/ssl/certs/derp.pem", a.rmempty = !0, a.validate = function(e, t) {
            return external_p.call(this, e, t, "keyfile");
        }, (a = t.option(external_n.Value, "keyfile", _("Key File"), _("Path to TLS private key (leave empty for auto)"))).placeholder = "/etc/ssl/private/derp.key", a.rmempty = !0, a.validate = function(e, t) {
            return external_p.call(this, e, t, "certfile");
        }, (a = (t = e.section(external_n.NamedSection, "external", "external", _("External Endpoint (Experimental)"), _("Acquire router port mappings and optionally publish the mapped endpoint into selected Tailnet policies."))).option(external_n.Flag, "enabled", _("Enable External Endpoint"), _("Acquire router port mappings and allow selected API instances to publish this endpoint"))).default = "0", a.rmempty = !1, a.validate = external_s, (a = t.option(external_n.DynamicList, "method", _("Mapping Methods"), _("Methods are attempted in this order"))).value("pcp", "PCP"), a.value("natpmp", "NAT-PMP"), a.value("upnp", "UPnP IGD"), a.default = [
            "pcp",
            "natpmp",
            "upnp"
        ], a.rmempty = !1, a.depends("enabled", "1"), (a = t.option(external_n.Value, "wan_interface", _("WAN Interface"), _("Use auto to follow the IPv4 default route, or enter a network interface name"))).default = "auto", a.rmempty = !1, a.depends("enabled", "1"), (a = t.option(external_n.Value, "derp_port", _("External DERP Port"), _("auto reads the actual local TCP listener and requests the same public port; the gateway may assign another port"))).default = "auto", a.rmempty = !1, a.validate = u, a.depends("enabled", "1"), (a = t.option(external_n.Value, "stun_port", _("External STUN Port"), _("auto reads the actual local UDP listener and requests the same public port; the gateway may assign another port"))).default = "auto", a.rmempty = !1, a.validate = u, a.depends("enabled", "1"), (a = t.option(external_n.Value, "lease_seconds", _("Mapping Lease (seconds)"))).default = "7200", a.rmempty = !1, a.datatype = "uinteger", a.depends("enabled", "1"), (a = t.option(external_n.Value, "retry_seconds", _("Retry Interval (seconds)"))).default = "60", a.rmempty = !1, a.datatype = "uinteger", a.depends("enabled", "1"), (a = t.option(external_n.Value, "sync_interval", _("DERP Map Sync Interval (seconds)"))).default = "300", a.rmempty = !1, a.datatype = "uinteger", a.depends("enabled", "1"), (a = t.option(external_n.Flag, "validate_endpoint", _("Validate Endpoint Locally"), _("Require a local NAT-loopback DERP/TLS and STUN check before publishing. This does not prove Internet reachability. Three consecutive failures withdraw the managed nodes until recovery."))).default = "0", a.rmempty = !1, a.depends("enabled", "1"), e.render();
    }
});


return main;