'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require tools.widgets as widgets';
'require poll';

// WARN: generated by rsbuild - do not edit

'require tools.views as views';
const main = views.LogreadBox("tailscale-derp", _("Tailscale DERP Log"));


return main;