'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require poll';

// WARN: generated by rsbuild - do not edit


// UNUSED EXPORTS: main

;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = null === n || "object" != typeof n || Array.isArray(n) ? {} : n, { children: l } = s, i = _object_without_properties(s, [
        "children"
    ]), f = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o instanceof Node ? o : String(o)));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...f), e;
    }
    if ("function" == typeof o) {
        let r = Reflect.apply(o, void 0, [
            _object_spread_props(_object_spread({}, i), {
                children: f
            })
        ]);
        if (!(r instanceof Node)) throw TypeError("JSX components must return a DOM Node");
        return r;
    }
    if ("string" != typeof o) throw TypeError("JSX element types must be tag names or component functions");
    let p = {}, c = _object_spread({}, i);
    for (let [e, t] of Object.entries(c))e.startsWith("on") && "function" == typeof t ? (p[e] = t, delete c[e]) : "boolean" == typeof t && (t ? c[e] = e : delete c[e]);
    let a = Object.keys(c).length > 0 ? f.length > 1 ? E(o, c, f) : E(o, c, f[0]) : f.length > 1 ? E(o, {}, f) : E(o, {}, f[0]);
    for (let [e, t] of Object.entries(p)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./src/views/peers.tsx

let peers_l = L.view, peers_n = L.rpc, peers_r = L.Poll, peers_o = peers_n.declare({
    object: "luci.tailscale-derp",
    method: "get_peers"
}), peers_c = peers_n.declare({
    object: "luci.tailscale-derp",
    method: "get_status"
});
function peers_d(t) {
    return t < 1024 ? "".concat(t, " B") : t < 1048576 ? "".concat((t / 1024).toFixed(1), " KB") : t < 1073741824 ? "".concat((t / 1048576).toFixed(1), " MB") : "".concat((t / 1073741824).toFixed(1), " GB");
}
function peers_a(l) {
    return 0 === l.length ? [
        jsx("tr", {
            class: "tr",
            children: jsx("td", {
                class: "td",
                colSpan: 4,
                style: "text-align: center;",
                children: _("No connected peers")
            })
        })
    ] : l.map((l)=>{
        var n;
        return jsxs("tr", {
            class: "tr",
            children: [
                jsx("td", {
                    class: "td",
                    style: "font-family: monospace;",
                    title: l.publicKey,
                    children: (n = l.publicKey).length > 20 ? n.substring(0, 16) + "..." : n
                }),
                jsx("td", {
                    class: "td",
                    children: l.remoteAddr
                }),
                jsx("td", {
                    class: "td",
                    children: function(t) {
                        try {
                            let e = new Date(t).getTime(), l = Date.now(), n = Math.max(0, l - e), r = Math.floor(n / 1000), o = Math.floor(r / 60), c = Math.floor(o / 60), d = Math.floor(c / 24);
                            if (d > 0) return _("%dd %dh %dm").format(d, c % 24, o % 60);
                            if (c > 0) return _("%dh %dm %ds").format(c, o % 60, r % 60);
                            if (o > 0) return _("%dm %ds").format(o, r % 60);
                            return _("%ds").format(r);
                        } catch (t) {
                            return "-";
                        }
                    }(l.connectedAt)
                }),
                jsx("td", {
                    class: "td",
                    children: function(t) {
                        try {
                            return new Date(t).toLocaleString();
                        } catch (e) {
                            return t;
                        }
                    }(l.connectedAt)
                })
            ]
        });
    });
}
const main = peers_l.extend({
    load: ()=>Promise.all([
            peers_o().catch(()=>({
                    peers: [],
                    count: 0
                })),
            peers_c().catch(()=>({}))
        ]),
    render (l) {
        var n, s;
        let i = l[0] || {}, h = l[1] || {}, u = i.peers || [], m = null != (n = h.bytesRecv) ? n : 0, f = null != (s = h.bytesSent) ? s : 0, p = jsx("div", {
            style: "margin-bottom: 0.75em; color: #333;",
            children: _("%d connected peer(s)").format(u.length)
        }), b = jsx("div", {
            style: "margin-bottom: 0.5em; color: #c00; min-height: 1.2em;"
        }), y = jsx("div", {
            style: "margin-bottom: 0.5em; color: #666; font-size: 0.9em;"
        }), v = jsx("div", {
            style: "margin-bottom: 0.75em; color: #333;",
            children: "\u2193 " + peers_d(m) + " / \u2191 " + peers_d(f)
        }), x = jsx("tbody", {});
        for (let t of (this.tableBody = x, this.countEl = p, this.errorEl = b, this.lastUpdatedEl = y, this.trafficEl = v, peers_a(u)))x.appendChild(t);
        return peers_r.add(()=>{
            var t;
            return t = this, Promise.all([
                peers_o(),
                peers_c()
            ]).then((e)=>{
                var l, n;
                let [r, o] = e, c = (null == r ? void 0 : r.peers) || [];
                t.countEl.textContent = _("%d connected peer(s)").format(c.length), t.errorEl.textContent = "", t.lastUpdatedEl.textContent = _("Last updated: %s").format(new Date().toLocaleTimeString());
                let s = null != (l = null == o ? void 0 : o.bytesRecv) ? l : 0, i = null != (n = null == o ? void 0 : o.bytesSent) ? n : 0;
                for(t.trafficEl.textContent = "\u2193 " + peers_d(s) + " / \u2191 " + peers_d(i); t.tableBody.firstChild;)t.tableBody.removeChild(t.tableBody.firstChild);
                for (let e of peers_a(c))t.tableBody.appendChild(e);
            }).catch((e)=>{
                let l = e instanceof Error ? e.message : "Backend unavailable";
                t.errorEl.textContent = l, t.countEl.textContent = "0 " + _("connected peer(s)");
            });
        }, 5), jsxs("div", {
            children: [
                jsx("h2", {
                    children: _("DERP Connected Peers")
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("h3", {
                            children: _("Connected Peers")
                        }),
                        p,
                        v,
                        y,
                        b,
                        jsxs("table", {
                            class: "table",
                            children: [
                                jsx("thead", {
                                    children: jsxs("tr", {
                                        class: "tr",
                                        children: [
                                            jsx("th", {
                                                class: "th",
                                                children: _("Public Key")
                                            }),
                                            jsx("th", {
                                                class: "th",
                                                children: _("Remote Address")
                                            }),
                                            jsx("th", {
                                                class: "th",
                                                children: _("Duration")
                                            }),
                                            jsx("th", {
                                                class: "th",
                                                children: _("Connected At")
                                            })
                                        ]
                                    })
                                }),
                                x
                            ]
                        })
                    ]
                })
            ]
        });
    },
    handleSave: null,
    handleSaveApply: null,
    handleReset: null
});


return main;