'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require tools.widgets as widgets';
'require poll';

// WARN: generated by rsbuild - do not edit


// UNUSED EXPORTS: main

;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = null === n || "object" != typeof n || Array.isArray(n) ? {} : n, { children: l } = s, i = _object_without_properties(s, [
        "children"
    ]), f = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o instanceof Node ? o : String(o)));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...f), e;
    }
    if ("function" == typeof o) {
        let r = Reflect.apply(o, void 0, [
            _object_spread_props(_object_spread({}, i), {
                children: f
            })
        ]);
        if (!(r instanceof Node)) throw TypeError("JSX components must return a DOM Node");
        return r;
    }
    if ("string" != typeof o) throw TypeError("JSX element types must be tag names or component functions");
    let p = {}, c = _object_spread({}, i);
    for (let [e, t] of Object.entries(c))e.startsWith("on") && "function" == typeof t ? (p[e] = t, delete c[e]) : "boolean" == typeof t && (t ? c[e] = e : delete c[e]);
    let a = Object.keys(c).length > 0 ? f.length > 1 ? E(o, c, f) : E(o, c, f[0]) : f.length > 1 ? E(o, {}, f) : E(o, {}, f[0]);
    for (let [e, t] of Object.entries(p)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./src/views/peers.tsx

let peers_n = L.rpc.declare({
    object: "luci.tailscale-derp",
    method: "get_peers"
});
function peers_l(e) {
    let t = new Date(e);
    return Number.isNaN(t.getTime()) ? "-" : t.toLocaleString();
}
function peers_i(e) {
    return e < 1024 ? "".concat(e, " B") : e < 1048576 ? "".concat((e / 1024).toFixed(1), " KB") : e < 1073741824 ? "".concat((e / 1048576).toFixed(1), " MB") : "".concat((e / 1073741824).toFixed(1), " GB");
}
function peers_o(e) {
    return null == e ? _("Sampling\u2026") : "".concat(peers_i(e), "/s");
}
function peers_d(e) {
    var t, n;
    return (null == (t = e.identity) ? void 0 : t.name) || (null == (n = e.identity) ? void 0 : n.hostname) || _("Unknown device");
}
function peers_r(n, l) {
    return jsxs("div", {
        class: "cbi-value",
        style: "padding: 0.3em 0;",
        children: [
            jsx("label", {
                class: "cbi-value-title",
                children: n
            }),
            jsx("div", {
                class: "cbi-value-field",
                style: "overflow-wrap: anywhere;",
                children: l || "-"
            })
        ]
    });
}
function peers_c(e, t) {
    return t ? peers_r(e, t) : null;
}
function peers_a(e) {
    var n, a, s;
    let u = e.identity;
    return jsxs("div", {
        children: [
            peers_r(_("Device"), peers_d(e)),
            peers_r(_("Identity Source"), u ? "official_api" === u.source ? _("Tailscale API") : _("Local tailscaled") : _("Unknown or resolving")),
            peers_r(_("Node Key"), e.publicKey),
            peers_c(_("Node ID"), null == u ? void 0 : u.nodeId),
            peers_c(_("Hostname"), null == u ? void 0 : u.hostname),
            peers_c(_("User"), null == u ? void 0 : u.user),
            peers_c(_("Addresses"), null == u || null == (n = u.addresses) ? void 0 : n.join(", ")),
            peers_c(_("OS"), null == u ? void 0 : u.os),
            peers_c(_("Client Version"), null == u ? void 0 : u.clientVersion),
            peers_c(_("Tags"), null == u || null == (a = u.tags) ? void 0 : a.join(", ")),
            peers_c(_("Sources"), null == u || null == (s = u.sources) ? void 0 : s.join(", ")),
            peers_r(_("Duration"), function(e) {
                let t = new Date(e).getTime();
                if (Number.isNaN(t)) return "-";
                let n = Math.floor(Math.max(0, Date.now() - t) / 1000), l = Math.floor(n / 60), i = Math.floor(l / 60), o = Math.floor(i / 24);
                return o ? _("%dd %dh %dm").format(o, i % 24, l % 60) : i ? _("%dh %dm %ds").format(i, l % 60, n % 60) : l ? _("%dm %ds").format(l, n % 60) : _("%ds").format(n);
            }(e.connectedAt)),
            peers_r(_("Connected At"), peers_l(e.connectedAt)),
            peers_r(_("Received (DERP payload)"), peers_i(e.bytesRecv)),
            peers_r(_("Sent (DERP payload)"), peers_i(e.bytesSent)),
            peers_r(_("Receive rate (5s)"), peers_o(e.recvBytesPerSecond)),
            peers_r(_("Send rate (5s)"), peers_o(e.sentBytesPerSecond)),
            jsxs("h4", {
                children: [
                    _("Connections"),
                    " (",
                    e.connections.length,
                    ")"
                ]
            }),
            e.connections.map((e)=>jsxs("div", {
                    style: "padding: 0.4em 0; border-top: 1px solid #ddd; overflow-wrap: anywhere;",
                    children: [
                        e.remoteAddr,
                        " \xb7 ",
                        peers_l(e.connectedAt)
                    ]
                }))
        ]
    });
}
function peers_s(n, l) {
    if (n.peers = l, n.countEl.textContent = _("%d connected peer(s)").format(l.length), n.listEl.replaceChildren(...l.length ? l.map((l)=>{
        var i;
        return jsxs("div", {
            style: "flex: 1 1 250px; min-width: 0; padding: 0.8em; border: 1px solid #ddd; border-radius: 4px; overflow-wrap: anywhere;",
            children: [
                jsx("div", {
                    style: "font-weight: bold;",
                    children: peers_d(l)
                }),
                jsx("div", {
                    style: "font-family: monospace; font-size: 0.85em;",
                    title: l.publicKey,
                    children: (i = l.publicKey).length > 24 ? "".concat(i.slice(0, 20), "\u2026") : i
                }),
                jsx("div", {
                    style: "margin-top: 0.4em;",
                    children: l.remoteAddr
                }),
                jsxs("div", {
                    style: "margin-top: 0.4em;",
                    children: [
                        "\u2193 ",
                        peers_o(l.recvBytesPerSecond),
                        " \xb7 \u2191 ",
                        peers_o(l.sentBytesPerSecond)
                    ]
                }),
                jsx("button", {
                    class: "cbi-button cbi-button-neutral",
                    type: "button",
                    style: "margin-top: 0.6em;",
                    onclick: ()=>{
                        let i;
                        return i = jsx("div", {
                            children: peers_a(l)
                        }), void (n.selectedKey = l.publicKey, n.dialogBody = i, L.ui.showModal(_("Peer Details"), jsxs("div", {
                            children: [
                                i,
                                jsx("div", {
                                    style: "margin-top: 1em; text-align: right;",
                                    children: jsx("button", {
                                        class: "cbi-button cbi-button-neutral",
                                        type: "button",
                                        onclick: ()=>{
                                            n.selectedKey = null, n.dialogBody = null, L.ui.hideModal();
                                        },
                                        children: _("Close")
                                    })
                                })
                            ]
                        })));
                    },
                    children: _("Details")
                })
            ]
        });
    }) : [
        jsx("p", {
            children: _("No connected peers")
        })
    ]), n.dialogBody && n.selectedKey) {
        let t = l.find((e)=>e.publicKey === n.selectedKey);
        n.dialogBody.replaceChildren(t ? peers_a(t) : jsx("p", {
            children: _("Peer disconnected")
        }));
    }
}
const main = L.view.extend({
    load: ()=>peers_n().catch(()=>({
                peers: [],
                count: 0,
                sampledAt: ""
            })),
    render (l) {
        let i = jsx("div", {
            style: "margin-bottom: 0.75em;"
        }), o = jsx("div", {
            style: "margin-bottom: 0.5em; min-height: 1.2em; color: #cf222e;"
        }), d = jsx("div", {
            style: "margin-bottom: 0.5em; font-size: 0.9em;"
        }), r = jsx("div", {
            style: "display: flex; flex-wrap: wrap; gap: 0.75em;"
        });
        return this.listEl = r, this.countEl = i, this.errorEl = o, this.lastUpdatedEl = d, this.selectedKey = null, this.dialogBody = null, peers_s(this, (null == l ? void 0 : l.peers) || []), L.Poll.add(()=>{
            var e;
            return e = this, peers_n().then((t)=>{
                peers_s(e, (null == t ? void 0 : t.peers) || []), e.errorEl.textContent = "", e.lastUpdatedEl.textContent = _("Last updated: %s").format(new Date().toLocaleTimeString());
            }).catch((t)=>{
                e.errorEl.textContent = t instanceof Error ? t.message : _("Backend unavailable");
            });
        }, 5), jsxs("div", {
            children: [
                jsx("h2", {
                    children: _("DERP Connected Peers")
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("h3", {
                            children: _("Connected Peers")
                        }),
                        i,
                        jsx("p", {
                            style: "font-size: 0.9em;",
                            children: _("Traffic counts DERP packet payload only; rates update about every 5 seconds.")
                        }),
                        d,
                        o,
                        r
                    ]
                })
            ]
        });
    },
    handleSave: null,
    handleSaveApply: null,
    handleReset: null
});


return main;