'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require poll';

// WARN: generated by rsbuild - do not edit


// UNUSED EXPORTS: main

;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = null === n || "object" != typeof n || Array.isArray(n) ? {} : n, { children: l } = s, i = _object_without_properties(s, [
        "children"
    ]), f = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o instanceof Node ? o : String(o)));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...f), e;
    }
    if ("function" == typeof o) {
        let r = Reflect.apply(o, void 0, [
            _object_spread_props(_object_spread({}, i), {
                children: f
            })
        ]);
        if (!(r instanceof Node)) throw TypeError("JSX components must return a DOM Node");
        return r;
    }
    if ("string" != typeof o) throw TypeError("JSX element types must be tag names or component functions");
    let p = {}, c = _object_spread({}, i);
    for (let [e, t] of Object.entries(c))e.startsWith("on") && "function" == typeof t ? (p[e] = t, delete c[e]) : "boolean" == typeof t && (t ? c[e] = e : delete c[e]);
    let a = Object.keys(c).length > 0 ? f.length > 1 ? E(o, c, f) : E(o, c, f[0]) : f.length > 1 ? E(o, {}, f) : E(o, {}, f[0]);
    for (let [e, t] of Object.entries(p)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./src/shared/config.ts


const pendingStatusStorageKey = "tailscale-derp.pendingStatus";
function isSocketAddress(e) {
    return /^(:\d+|[^\s:]+:\d+)$/.test(e);
}
function validateSocketAddress(e, t) {
    return t ? !!isSocketAddress(t) || "".concat(e, " must be in :port or host:port format") : "".concat(e, " is required");
}
function validateUnixSocketPath(e, t) {
    return t ? !(!t.startsWith("/") || /[\r\n]/.test(t)) || "".concat(e, " must be an absolute Unix socket path") : "".concat(e, " is required");
}
function firstOption(e, t, o) {
    let n = e.lookupOption(o, t);
    return n ? n[0] : null;
}
function optionFormValue(e, t, o, n) {
    let r = firstOption(e, t, o), s = null == r ? void 0 : r.formvalue(t);
    return null == s || "" === s ? n : String(s);
}
function boolFormValue(e, t, o, n) {
    let r = optionFormValue(e, t, o, n ? "1" : "0");
    return "1" === r || "true" === r;
}
function captureExpectedStatus(e) {
    return {
        enabled: boolFormValue(e, "global", "enabled", !0),
        listen: optionFormValue(e, "global", "listen", ":3478"),
        stun: boolFormValue(e, "global", "stun", !0),
        mesh: boolFormValue(e, "mesh", "enabled", !1),
        opsSocket: optionFormValue(e, "ops", "socket", "/var/run/tailscale-derp/ops.sock"),
        health: optionFormValue(e, "ops", "health", ":9912")
    };
}
function savePendingStatus(o) {
    if (!window.sessionStorage) return;
    let n = t(e({}, o), {
        savedAt: Date.now()
    });
    window.sessionStorage.setItem(pendingStatusStorageKey, JSON.stringify(n));
}
function clearPendingStatus() {
    window.sessionStorage && window.sessionStorage.removeItem(pendingStatusStorageKey);
}
function readPendingStatus() {
    if (!window.sessionStorage) return null;
    try {
        let e = window.sessionStorage.getItem(pendingStatusStorageKey);
        return e ? JSON.parse(e) : null;
    } catch (e) {
        return window.sessionStorage.removeItem(pendingStatusStorageKey), null;
    }
}

;// CONCATENATED MODULE: ./src/shared/external.ts
let external_e = L.rpc;
const callExternalStatus = external_e.declare({
    object: "luci.tailscale-derp",
    method: "get_external_status"
});
const externalActionCalls = {
    reconcile: external_e.declare({
        object: "luci.tailscale-derp",
        method: "reconcile_external"
    }),
    check: external_e.declare({
        object: "luci.tailscale-derp",
        method: "check_external"
    }),
    sync: external_e.declare({
        object: "luci.tailscale-derp",
        method: "sync_derpmap"
    })
};

;// CONCATENATED MODULE: ./src/views/status.tsx



let status_r = L.view, status_o = L.rpc, status_s = L.ui, status_i = L.Poll, status_d = {
    start: status_o.declare({
        object: "luci.tailscale-derp",
        method: "start"
    }),
    stop: status_o.declare({
        object: "luci.tailscale-derp",
        method: "stop"
    }),
    restart: status_o.declare({
        object: "luci.tailscale-derp",
        method: "restart"
    }),
    reload: status_o.declare({
        object: "luci.tailscale-derp",
        method: "reload_config"
    })
}, status_h = status_o.declare({
    object: "luci.tailscale-derp",
    method: "get_status"
}), status_u = status_o.declare({
    object: "luci.tailscale-derp",
    method: "get_version"
});
function b(t) {
    return t < 1024 ? "".concat(t, " B") : t < 1048576 ? "".concat((t / 1024).toFixed(1), " KB") : t < 1073741824 ? "".concat((t / 1048576).toFixed(1), " MB") : "".concat((t / 1073741824).toFixed(1), " GB");
}
function status_f(t) {
    var e, n, l, c, a, r, o, s;
    let i = [];
    t.verifyURLsEnabled && i.push(_("URLs")), t.verifyTailscaled && i.push(_("tailscaled")), t.verifyAPIEnabled && i.push(_("Official API"));
    let d = t.verifyEnabled ? i.length ? i.join(", ") : _("Enabled, but no methods configured") : _("Disabled");
    return t.verifyAPIInstances && t.verifyAPIInstances > 0 && (d += " (".concat(t.verifyAPIInstances, " ").concat(_("API instance(s)"), ")")), (null == (s = t.verifyClients) ? void 0 : s.length) && (d += "; ".concat(t.verifyClients.join(", "))), {
        verifyClients: d,
        running: !!t.running,
        listen: t.listen || _("N/A"),
        stun: t.stun ? _("Yes") : _("No"),
        mesh: t.mesh ? _("Yes") : _("No"),
        opsSocket: t.opsSocket || _("N/A"),
        health: t.health || _("N/A"),
        error: t.error || "",
        clients: null != (e = t.clients) ? e : 0,
        accepts: null != (n = t.accepts) ? n : 0,
        bytesRecv: null != (l = t.bytesRecv) ? l : 0,
        bytesSent: null != (c = t.bytesSent) ? c : 0,
        bytesRecvTotal: null != (a = t.bytesRecvTotal) ? a : 0,
        bytesSentTotal: null != (r = t.bytesSentTotal) ? r : 0,
        acceptsTotal: null != (o = t.acceptsTotal) ? o : 0,
        trafficPersist: !!t.trafficPersist
    };
}
function status_E(t) {
    let e = t.endpoint;
    if (!(null == e ? void 0 : e.ipv4) || !e.derpPort) return _("Not mapped");
    let n = -1 === e.stunPort ? _("STUN disabled") : "UDP ".concat(e.ipv4, ":").concat(e.stunPort || 3478);
    return "TCP ".concat(e.ipv4, ":").concat(e.derpPort, "; ").concat(n);
}
function status_p(t) {
    let e = t.validation || {};
    if (!t.validationEnabled && (!e.state || "disabled" === e.state)) return "".concat(_("Disabled"), " (").concat(_("local NAT loopback only"), ")");
    let n = e.state || _("Unknown"), l = e.scope || "local_nat_loopback";
    return "".concat(n, " (").concat(l, ")").concat(e.error ? ": ".concat(e.error) : "");
}
function v(n) {
    let l = n.instances || [];
    return l.length ? l.map((n)=>jsxs("div", {
            children: [
                jsx("strong", {
                    children: n.label || n.name || _("Unnamed instance")
                }),
                ": ".concat(n.state || _("Unknown")).concat(n.error ? " - ".concat(n.error) : "")
            ]
        })) : [
        jsx("span", {
            children: _("No synchronized instances")
        })
    ];
}
function status_x(t, e) {
    var n, l;
    t.externalStateEl.textContent = e.state || (e.enabled ? _("Unknown") : _("Disabled")), t.externalEndpointEl.textContent = status_E(e), t.externalMethodEl.textContent = (null == (n = e.endpoint) ? void 0 : n.method) || _("N/A"), t.externalLeaseEl.textContent = (null == (l = e.endpoint) ? void 0 : l.leaseUntil) || _("N/A"), t.externalValidationEl.textContent = status_p(e), t.externalFailuresEl.textContent = "".concat(e.failureCount || 0, "/").concat(e.failureThreshold || 3), t.externalErrorEl.textContent = e.error || _("None"), t.externalInstancesEl.replaceChildren(...v(e));
}
function status_y(t) {
    if (!t) return "";
    if (/^:\d+$/.test(t)) return "0.0.0.0".concat(t);
    let e = t.match(/^\[::\]:(\d+)$/);
    return e ? "0.0.0.0:".concat(e[1]) : t;
}
function m(t, e) {
    let n = readPendingStatus();
    return n ? !n.savedAt || Date.now() - n.savedAt > 300000 ? {
        color: "#c60",
        text: _("Saved configuration status expired before it could be confirmed."),
        clear: !0
    } : t && n && (!1 === n.enabled ? "" !== t.error || !1 === t.running : !0 === t.running && status_y(t.listen) === status_y(n.listen) && t.stun === (n.stun ? _("Yes") : _("No")) && t.mesh === (n.mesh ? _("Yes") : _("No")) && t.opsSocket === n.opsSocket && t.health === n.health) ? {
        color: "#1a7f37",
        text: _("Saved configuration is now active."),
        clear: !0
    } : {
        color: "#c60",
        text: e ? "".concat(_("Waiting for saved configuration to become active:"), " ").concat(e) : _("Waiting for saved configuration to become active..."),
        clear: !1
    } : {
        color: "inherit",
        text: _("No configuration change pending."),
        clear: !1
    };
}
function C(t) {
    return Promise.all([
        status_h(),
        status_u(),
        callExternalStatus().catch((t)=>({
                state: "unavailable",
                error: t instanceof Error ? t.message : _("External endpoint backend unavailable")
            }))
    ]).then((e)=>{
        let [l, c, a] = e, r = status_f(l || {});
        t.statusEl.textContent = r.running ? _("Running") : _("Stopped"), t.versionEl.textContent = r.error ? _("Unavailable") : (null == c ? void 0 : c.version) || _("Unknown"), t.listenEl.textContent = r.error ? _("Unavailable") : r.listen, t.stunEl.textContent = r.error ? _("Unknown") : r.stun, t.meshEl.textContent = r.error ? _("Unknown") : r.mesh, t.verifyClientsEl.textContent = r.error ? _("Unknown") : r.verifyClients, t.opsSocketEl.textContent = r.error ? _("Unavailable") : r.opsSocket, t.healthEl.textContent = r.error ? _("Unavailable") : r.health, t.errorEl.textContent = r.error || _("None"), t.clientsEl.textContent = "".concat(r.clients, " ").concat(_("connected"), " (").concat(r.accepts, " ").concat(_("total accepted"), ")"), r.trafficPersist ? (t.trafficEl.textContent = "Session: \u2193 ".concat(b(r.bytesRecv), " / \u2191 ").concat(b(r.bytesSent)), t.trafficTotalEl.textContent = "Total: \u2193 ".concat(b(r.bytesRecvTotal), " / \u2191 ").concat(b(r.bytesSentTotal)), t.trafficTotalEl.style.display = "") : (t.trafficEl.textContent = "\u2193 ".concat(b(r.bytesRecv), " / \u2191 ").concat(b(r.bytesSent)), t.trafficTotalEl.style.display = "none");
        let o = m(r, r.error);
        o.clear && clearPendingStatus(), t.syncEl.style.color = o.color, t.syncEl.textContent = o.text, status_x(t, a || {});
    }).catch((e)=>{
        let l = e instanceof Error ? e.message : _("Status backend unavailable");
        t.statusEl.textContent = _("Offline"), t.versionEl.textContent = _("Unavailable"), t.listenEl.textContent = _("Unavailable"), t.stunEl.textContent = _("Unknown"), t.meshEl.textContent = _("Unknown"), t.verifyClientsEl.textContent = _("Unknown"), t.opsSocketEl.textContent = _("Unavailable"), t.healthEl.textContent = _("Unavailable"), t.errorEl.textContent = l || _("Status backend unavailable"), t.clientsEl.textContent = "0 ".concat(_("connected"), " (0 ").concat(_("total accepted"), ")"), t.trafficEl.textContent = "\u2193 0 B / \u2191 0 B", t.trafficTotalEl.textContent = "", t.trafficTotalEl.style.display = "none";
        let c = m(null, l || _("Status backend unavailable"));
        c.clear && clearPendingStatus(), t.syncEl.style.color = c.color, t.syncEl.textContent = c.text, status_x(t, {
            state: "unavailable",
            error: l
        });
    });
}
const main = status_r.extend({
    handleAction (t) {
        let e = function(t) {
            switch(t){
                case "start":
                    return _("Start");
                case "stop":
                    return _("Stop");
                case "restart":
                    return _("Restart");
                case "reload":
                    return _("Reload");
            }
        }(t);
        if ("stop" === t || "restart" === t) {
            let n = "".concat(_("Are you sure you want to"), " ").concat(t, " ").concat(_("the DERP service?"));
            if (!window.confirm(n)) return this.resultEl.style.color = "#cf222e", this.resultEl.textContent = "".concat(e, " ").concat(_("cancelled.")), Promise.resolve();
        }
        for (let t of this.actionButtons)t.disabled = !0;
        return this.resultEl.style.color = "#1a7f37", this.resultEl.textContent = "".concat(e, " ").concat(_("in progress...")), status_d[t]().then((t)=>{
            let n = t || {}, l = n.result || "ok", c = n.error;
            if ("ok" !== l || c) throw Error(c || "".concat(e, " ").concat(_("failed")));
            return this.resultEl.style.color = "#1a7f37", this.resultEl.textContent = "".concat(e, " ").concat(_("completed successfully.")), C(this);
        }).catch((t)=>{
            let n = t instanceof Error ? t.message : _("unknown error");
            return this.resultEl.style.color = "#cf222e", this.resultEl.textContent = "".concat(e, " ").concat(_("failed:"), " ").concat(n), C(this);
        }).finally(()=>{
            for (let t of this.actionButtons)t.disabled = !1;
        });
    },
    handleExternalAction (t) {
        let e = function(t) {
            switch(t){
                case "reconcile":
                    return _("Remap Now");
                case "check":
                    return _("Check Locally");
                case "sync":
                    return _("Sync DERP Map");
            }
        }(t);
        for (let t of this.externalButtons)t.disabled = !0;
        return this.resultEl.style.color = "#1a7f37", this.resultEl.textContent = "".concat(e, " ").concat(_("in progress...")), externalActionCalls[t]().then((t)=>{
            if ((null == t ? void 0 : t.result) !== "ok" || t.error) throw Error((null == t ? void 0 : t.error) || "".concat(e, " ").concat(_("failed")));
            return this.resultEl.style.color = "#1a7f37", this.resultEl.textContent = "".concat(e, " ").concat(_("completed successfully.")), C(this);
        }).catch((t)=>{
            let n = t instanceof Error ? t.message : _("unknown error");
            return this.resultEl.style.color = "#cf222e", this.resultEl.textContent = "".concat(e, " ").concat(_("failed:"), " ").concat(n), C(this);
        }).finally(()=>{
            for (let t of this.externalButtons)t.disabled = !1;
        });
    },
    load: ()=>Promise.all([
            status_h().catch((t)=>({
                    error: t instanceof Error ? t.message : _("Status backend unavailable")
                })),
            status_u().catch(()=>({
                    version: _("Unavailable")
                })),
            callExternalStatus().catch((t)=>({
                    state: "unavailable",
                    error: t instanceof Error ? t.message : _("External endpoint backend unavailable")
                }))
        ]),
    render (l) {
        var c, a;
        let r = l[0] || {}, o = l[1] || {}, d = status_f(r), h = l[2] || {}, u = m(d, d.error);
        u.clear && clearPendingStatus();
        let x = status_s.createHandlerFn(this, "handleAction", "start"), y = status_s.createHandlerFn(this, "handleAction", "stop"), k = status_s.createHandlerFn(this, "handleAction", "restart"), S = status_s.createHandlerFn(this, "handleAction", "reload"), g = status_s.createHandlerFn(this, "handleExternalAction", "reconcile"), U = status_s.createHandlerFn(this, "handleExternalAction", "check"), A = status_s.createHandlerFn(this, "handleExternalAction", "sync"), T = jsx("td", {
            class: "td",
            children: d.running ? _("Running") : _("Stopped")
        }), w = jsx("td", {
            class: "td",
            children: d.error ? _("Unavailable") : o.version || _("Unknown")
        }), N = jsx("td", {
            class: "td",
            children: d.error ? _("Unavailable") : d.listen
        }), R = jsx("td", {
            class: "td",
            children: d.error ? _("Unknown") : d.stun
        }), P = jsx("td", {
            class: "td",
            children: d.error ? _("Unknown") : d.mesh
        }), F = jsx("td", {
            class: "td",
            children: d.error ? _("Unknown") : d.verifyClients
        }), I = jsx("td", {
            class: "td",
            children: d.error ? _("Unavailable") : d.opsSocket
        }), B = jsx("td", {
            class: "td",
            children: d.error ? _("Unavailable") : d.health
        }), j = jsx("td", {
            class: "td",
            children: d.error || _("None")
        }), D = jsx("td", {
            class: "td",
            children: "".concat(d.clients, " ").concat(_("connected"), " (").concat(d.accepts, " ").concat(_("total accepted"), ")")
        }), M = jsx("td", {
            class: "td",
            children: "\u2193 ".concat(b(d.bytesRecv), " / \u2191 ").concat(b(d.bytesSent))
        }), H = jsx("td", {
            class: "td",
            style: "display: none;"
        }), V = jsx("td", {
            class: "td",
            children: h.state || (h.enabled ? _("Unknown") : _("Disabled"))
        }), Y = jsx("td", {
            class: "td",
            children: status_E(h)
        }), O = jsx("td", {
            class: "td",
            children: (null == (c = h.endpoint) ? void 0 : c.method) || _("N/A")
        }), z = jsx("td", {
            class: "td",
            children: (null == (a = h.endpoint) ? void 0 : a.leaseUntil) || _("N/A")
        }), W = jsx("td", {
            class: "td",
            children: status_p(h)
        }), $ = jsx("td", {
            class: "td",
            children: "".concat(h.failureCount || 0, "/").concat(h.failureThreshold || 3)
        }), G = jsx("td", {
            class: "td",
            children: h.error || _("None")
        }), K = jsx("td", {
            class: "td",
            children: v(h)
        });
        d.trafficPersist && (M.textContent = "Session: \u2193 ".concat(b(d.bytesRecv), " / \u2191 ").concat(b(d.bytesSent)), H.textContent = "Total: \u2193 ".concat(b(d.bytesRecvTotal), " / \u2191 ").concat(b(d.bytesSentTotal)), H.style.display = "");
        let q = jsx("div", {
            style: "margin-bottom: 0.75em; color: ".concat(u.color, ";"),
            children: u.text
        }), J = jsx("div", {
            style: "margin-top: 0.75em; min-height: 1.2em; color: #1a7f37;",
            children: _("No action executed yet.")
        });
        this.statusEl = T, this.versionEl = w, this.listenEl = N, this.stunEl = R, this.meshEl = P, this.verifyClientsEl = F, this.opsSocketEl = I, this.healthEl = B, this.errorEl = j, this.clientsEl = D, this.trafficEl = M, this.trafficTotalEl = H, this.syncEl = q, this.resultEl = J, this.externalStateEl = V, this.externalEndpointEl = Y, this.externalMethodEl = O, this.externalLeaseEl = z, this.externalValidationEl = W, this.externalFailuresEl = $, this.externalErrorEl = G, this.externalInstancesEl = K;
        let Q = jsx("button", {
            class: "cbi-button cbi-button-action",
            onclick: x,
            children: _("Start")
        }), X = jsx("button", {
            class: "cbi-button cbi-button-negative",
            onclick: y,
            children: _("Stop")
        }), Z = jsx("button", {
            class: "cbi-button cbi-button-action",
            onclick: k,
            children: _("Restart")
        }), tt = jsx("button", {
            class: "cbi-button cbi-button-action",
            onclick: S,
            children: _("Reload Config")
        }), te = jsx("button", {
            class: "cbi-button cbi-button-action",
            onclick: g,
            children: _("Remap Now")
        }), tn = jsx("button", {
            class: "cbi-button cbi-button-action",
            onclick: U,
            children: _("Check Locally")
        }), tl = jsx("button", {
            class: "cbi-button cbi-button-action",
            onclick: A,
            children: _("Sync DERP Map")
        });
        return this.actionButtons = [
            Q,
            X,
            Z,
            tt
        ], this.externalButtons = [
            te,
            tn,
            tl
        ], status_i.add(()=>C(this), 5), jsxs("div", {
            children: [
                jsx("h2", {
                    children: _("Tailscale DERP Status")
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("h3", {
                            children: _("DERP Server Status")
                        }),
                        q,
                        jsxs("table", {
                            class: "table",
                            children: [
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Service Status")
                                        }),
                                        T
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Version")
                                        }),
                                        w
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Connected Clients")
                                        }),
                                        D
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Traffic")
                                        }),
                                        M
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Traffic (Total)")
                                        }),
                                        H
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Listen Address")
                                        }),
                                        N
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("STUN Enabled")
                                        }),
                                        R
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Mesh Enabled")
                                        }),
                                        P
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Verify Clients")
                                        }),
                                        F
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Ops Unix Socket")
                                        }),
                                        I
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Health Address")
                                        }),
                                        B
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Last Error")
                                        }),
                                        j
                                    ]
                                })
                            ]
                        })
                    ]
                }),
                jsxs("div", {
                    class: "cbi-section",
                    style: "margin-top: 1em;",
                    children: [
                        jsx("h3", {
                            children: _("External Endpoint (Experimental)")
                        }),
                        jsx("p", {
                            children: _("The optional availability check runs from this router through NAT loopback. A pass does not prove Internet reachability, and a failure may only mean that the gateway does not support hairpin NAT.")
                        }),
                        jsxs("table", {
                            class: "table",
                            children: [
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("State")
                                        }),
                                        V
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Mapped Endpoint")
                                        }),
                                        Y
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Mapping Method")
                                        }),
                                        O
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Lease Until")
                                        }),
                                        z
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Local NAT-loopback Check")
                                        }),
                                        W
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Consecutive Failures")
                                        }),
                                        $
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("Tailnet Instances")
                                        }),
                                        K
                                    ]
                                }),
                                jsxs("tr", {
                                    class: "tr",
                                    children: [
                                        jsx("td", {
                                            class: "td",
                                            children: _("External Error")
                                        }),
                                        G
                                    ]
                                })
                            ]
                        }),
                        jsxs("div", {
                            class: "cbi-section-node",
                            style: "margin-top: 0.75em;",
                            children: [
                                te,
                                " ",
                                " ",
                                " ",
                                tn,
                                " ",
                                " ",
                                " ",
                                tl
                            ]
                        })
                    ]
                }),
                jsxs("div", {
                    class: "cbi-section",
                    style: "margin-top: 1em;",
                    children: [
                        jsx("h3", {
                            children: _("Service Actions")
                        }),
                        jsxs("div", {
                            class: "cbi-section-node",
                            children: [
                                Q,
                                " ",
                                X,
                                " ",
                                Z,
                                " ",
                                tt
                            ]
                        }),
                        J
                    ]
                })
            ]
        });
    },
    handleSave: null,
    handleSaveApply: null,
    handleReset: null
});


return main;