'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require tools.widgets as widgets';
'require poll';

// WARN: generated by rsbuild - do not edit


// UNUSED EXPORTS: main

;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = null === n || "object" != typeof n || Array.isArray(n) ? {} : n, { children: l } = s, i = _object_without_properties(s, [
        "children"
    ]), f = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o instanceof Node ? o : String(o)));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...f), e;
    }
    if ("function" == typeof o) {
        let r = Reflect.apply(o, void 0, [
            _object_spread_props(_object_spread({}, i), {
                children: f
            })
        ]);
        if (!(r instanceof Node)) throw TypeError("JSX components must return a DOM Node");
        return r;
    }
    if ("string" != typeof o) throw TypeError("JSX element types must be tag names or component functions");
    let p = {}, c = _object_spread({}, i);
    for (let [e, t] of Object.entries(c))e.startsWith("on") && "function" == typeof t ? (p[e] = t, delete c[e]) : "boolean" == typeof t && (t ? c[e] = e : delete c[e]);
    let a = Object.keys(c).length > 0 ? f.length > 1 ? E(o, c, f) : E(o, c, f[0]) : f.length > 1 ? E(o, {}, f) : E(o, {}, f[0]);
    for (let [e, t] of Object.entries(p)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./src/shared/tailnets.ts
let tailnets_e = L.rpc;
const callTailnets = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "get_tailnets",
    reject: !0
});
const callTailnetACL = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "get_tailnet_acl",
    params: [
        "instance"
    ],
    reject: !0
});
const callValidateTailnetACL = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "validate_tailnet_acl",
    params: [
        "instance",
        "hujson"
    ],
    reject: !0
});
const callSetTailnetACL = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "set_tailnet_acl",
    params: [
        "instance",
        "hujson",
        "etag"
    ],
    reject: !0
});

;// CONCATENATED MODULE: ./src/shared/monaco.ts
let monaco_e, monaco_o;


let monaco_n = "0.56.0", monaco_a = "0.56.1", monaco_s = "https://raw.githubusercontent.com/joneskoo/tailscale/claude/tailscale-acl-json-schema-v2/acl-schema.json", monaco_l = [
    {
        id: "esm",
        name: "esm.sh",
        moduleUrl: "https://esm.sh/monaco-editor@".concat(monaco_n, "?bundle"),
        probeUrls: [
            "https://esm.sh/monaco-editor@".concat(monaco_n, "/es2022/monaco-editor.bundle.mjs")
        ],
        editorWorkerUrl: "https://esm.sh/monaco-editor@".concat(monaco_n, "/esm/vs/editor/editor.worker.js"),
        jsonWorkerUrl: "https://esm.sh/monaco-editor@".concat(monaco_n, "/esm/vs/language/json/json.worker.js"),
        styleUrl: "https://esm.sh/monaco-editor@".concat(monaco_n, "/min/vs/editor/editor.main.css")
    },
    ...[
        [
            "jsdelivr",
            "jsDelivr",
            "https://cdn.jsdelivr.net/npm/@node-projects/monaco-editor-esm"
        ],
        [
            "fastly",
            "jsDelivr (Fastly)",
            "https://fastly.jsdelivr.net/npm/@node-projects/monaco-editor-esm"
        ],
        [
            "gcore",
            "jsDelivr (Gcore)",
            "https://gcore.jsdelivr.net/npm/@node-projects/monaco-editor-esm"
        ],
        [
            "unpkg",
            "unpkg",
            "https://unpkg.com/@node-projects/monaco-editor-esm"
        ]
    ].map((e)=>{
        let [o, r, t] = e;
        return {
            id: o,
            name: r,
            moduleUrl: "".concat(t, "@").concat(monaco_a, "/esm/vs/editor/editor.api.js"),
            jsonModuleUrl: "".concat(t, "@").concat(monaco_a, "/esm/vs/languages/features/json/register.js"),
            jsonModeUrl: "".concat(t, "@").concat(monaco_a, "/esm/vs/languages/features/json/jsonMode.js"),
            editorWorkerUrl: "".concat(t, "@").concat(monaco_a, "/esm/vs/editor/editor.worker.js"),
            jsonWorkerUrl: "".concat(t, "@").concat(monaco_a, "/esm/vs/language/json/json.worker.js"),
            styleUrl: "".concat(t, "@").concat(monaco_a, "/min/vs/editor/editor.main.css")
        };
    })
];
function monaco_c(e) {
    let o = new Blob([
        "import ".concat(JSON.stringify(e), ";")
    ], {
        type: "application/javascript"
    }), r = URL.createObjectURL(o);
    try {
        return new Worker(r, {
            type: "module"
        });
    } finally{
        URL.revokeObjectURL(r);
    }
}
function monaco_i(e) {
    return Function("url", "return import(url);")(e);
}
async function monaco_d(e) {
    let o = new AbortController(), r = window.setTimeout(()=>o.abort(), 15000), t = performance.now();
    try {
        var n;
        let r = (null != (n = e.probeUrls) ? n : [
            e.moduleUrl,
            e.jsonModuleUrl,
            e.jsonModeUrl
        ]).filter((e)=>!!e), a = await Promise.all(r.map((e)=>fetch(e, {
                signal: o.signal
            })));
        if (a.some((e)=>!e.ok)) throw Error("Monaco CDN probe failed.");
        return await Promise.all(a.map((e)=>e.arrayBuffer())), performance.now() - t;
    } finally{
        window.clearTimeout(r);
    }
}
async function monaco_m() {
    return (await Promise.all(monaco_l.map(async (e, o)=>{
        try {
            return {
                candidate: e,
                duration: await monaco_d(e),
                index: o
            };
        } catch (r) {
            return {
                candidate: e,
                duration: 1 / 0,
                index: o
            };
        }
    }))).sort((e, o)=>e.duration - o.duration || e.index - o.index).map((e)=>{
        let { candidate: o } = e;
        return o;
    });
}
async function u(e) {
    let o;
    for (let r of e)try {
        return await function(e) {
            var o, r;
            let t = (o = e.styleUrl, new Promise((e, r)=>{
                let t = document.createElement("link");
                t.rel = "stylesheet", t.href = o, t.onload = ()=>e(t), t.onerror = ()=>{
                    t.remove(), r(Error("Unable to load Monaco stylesheet from ".concat(o, ".")));
                }, document.head.appendChild(t);
            })), n = monaco_i(e.moduleUrl), a = e.jsonModuleUrl && e.jsonModeUrl ? Promise.all([
                monaco_i(e.jsonModuleUrl),
                monaco_i(e.jsonModeUrl)
            ]).then((e)=>{
                let [o] = e;
                return o.jsonDefaults;
            }) : n.then((e)=>{
                var o;
                if (!(null == (o = e.json) ? void 0 : o.jsonDefaults)) throw Error("Monaco JSON support is unavailable.");
                return e.json.jsonDefaults;
            });
            return (r = Promise.all([
                n,
                a,
                t
            ]).then((o)=>{
                let [r, t, n] = o;
                return {
                    monaco: r,
                    jsonDefaults: t,
                    createEditorWorker: ()=>monaco_c(e.editorWorkerUrl),
                    createJsonWorker: ()=>monaco_c(e.jsonWorkerUrl),
                    style: n
                };
            }), new Promise((e, o)=>{
                let t = window.setTimeout(()=>o(Error("Monaco CDN request timed out.")), 15000);
                r.then((o)=>{
                    window.clearTimeout(t), e(o);
                }, (e)=>{
                    window.clearTimeout(t), o(e);
                });
            })).catch((o)=>{
                throw t.then((e)=>e.remove(), ()=>void 0), Error("Unable to load Monaco from ".concat(e.name, "."), {
                    cause: o
                });
            });
        }(r);
    } catch (e) {
        o = e;
    }
    throw null != o ? o : Error("Unable to load Monaco from any CDN.");
}
async function createMonacoTextEditor(n, a, c) {
    let i = arguments.length > 3 && void 0 !== arguments[3] ? arguments[3] : "auto", d = await function(n) {
        if (monaco_e) return monaco_e;
        let a = Promise.all([
            "auto" === n ? monaco_m() : Promise.resolve(monaco_l.filter((e)=>e.id === n)),
            monaco_o || (monaco_o = fetch(monaco_s).then((e)=>{
                if (!e.ok) throw Error("Unable to load the Tailscale ACL schema.");
                return e.json();
            }).catch(()=>void 0))
        ]).then((e)=>{
            let [o, n] = e;
            return u(o).then((e)=>{
                var o, a;
                let l, c;
                return o = e.createEditorWorker, a = e.createJsonWorker, c = (l = globalThis).MonacoEnvironment, l.MonacoEnvironment = _object_spread_props(_object_spread({}, c), {
                    getWorker: (e, r)=>(null == c ? void 0 : c.getWorker) ? c.getWorker(e, r) : ("json" === r ? a : o)()
                }), e.jsonDefaults.setDiagnosticsOptions({
                    allowComments: !0,
                    enableSchemaRequest: !1,
                    schemas: n ? [
                        {
                            fileMatch: [
                                "*"
                            ],
                            schema: n,
                            uri: monaco_s
                        }
                    ] : [],
                    trailingCommas: "ignore",
                    validate: !0
                }), e.monaco;
            });
        });
        return monaco_e = a, a.catch(()=>{
            monaco_e === a && (monaco_e = void 0);
        }), a;
    }(i), p = d.editor.createModel(a(), "json");
    d.editor.setTheme(!function() {
        for (let e of [
            document.body,
            document.documentElement
        ]){
            let o = function(e) {
                var o;
                let r = null == (o = getComputedStyle(e).backgroundColor.match(/\d+/g)) ? void 0 : o.map(Number);
                if (r && !(r.length < 3) && 0 !== r[3]) return 0.299 * r[0] + 0.587 * r[1] + 0.114 * r[2];
            }(e);
            if (void 0 !== o) return o < 128;
        }
        return matchMedia("(prefers-color-scheme: dark)").matches;
    }() ? "vs" : "vs-dark");
    let h = d.editor.create(n, {
        automaticLayout: !0,
        minimap: {
            enabled: !1
        },
        model: p,
        scrollBeyondLastLine: !1,
        tabSize: 2,
        wordWrap: "on"
    }), j = p.onDidChangeContent(()=>c(p.getValue()));
    return {
        getValue: ()=>p.getValue(),
        setValue (e) {
            p.setValue(e);
        },
        dispose () {
            j.dispose(), h.dispose(), p.dispose();
        }
    };
}

;// CONCATENATED MODULE: ./src/views/tailnets.tsx



let tailnets_o = L.view;
function tailnets_r(e, i) {
    let l = arguments.length > 2 && void 0 !== arguments[2] ? arguments[2] : "";
    e.messageEl.style.color = l, e.messageEl.textContent = i;
}
function tailnets_s(e, i) {
    e.validateEl.disabled = i, e.saveEl.disabled = i;
}
function tailnets_d(e) {
    var i, l;
    return null != (i = null == (l = e.policyEditor) ? void 0 : l.getValue()) ? i : e.policyEl.value;
}
function tailnets_u(e, i) {
    var l;
    e.policyEl.value = i, null == (l = e.policyEditor) || l.setValue(i);
}
function v(l) {
    let n = l.tailnets.find((e)=>e.name === l.instance);
    n ? l.metadataEl.replaceChildren(jsxs("div", {
        class: "cbi-value",
        children: [
            jsx("label", {
                class: "cbi-value-title",
                children: _("Tailnet")
            }),
            jsx("div", {
                class: "cbi-value-field",
                children: n.tailnet || "-"
            })
        ]
    }), jsxs("div", {
        class: "cbi-value",
        children: [
            jsx("label", {
                class: "cbi-value-title",
                children: _("Instance")
            }),
            jsx("div", {
                class: "cbi-value-field",
                style: "font-family: monospace;",
                children: n.name || "-"
            })
        ]
    })) : l.metadataEl.replaceChildren(jsx("p", {
        children: _("Select a configured API instance to manage its ACL policy.")
    }));
}
function tailnets_h(e) {
    let i = arguments.length > 1 && void 0 !== arguments[1] && arguments[1], l = e.instance;
    if (!l) return tailnets_r(e, _("Select an API instance first."), "#cf222e"), Promise.resolve();
    let t = ++e.loadGeneration, a = tailnets_d(e);
    return tailnets_s(e, !0), tailnets_r(e, _("Loading ACL policy...")), callTailnetACL(l).then((l)=>{
        if (t === e.loadGeneration) {
            if (null == l ? void 0 : l.error) throw Error(l.error);
            e.etag = (null == l ? void 0 : l.etag) || "", i || tailnets_u(e, (null == l ? void 0 : l.hujson) || ""), tailnets_r(e, i ? _("The server policy changed. Your draft was retained; review it before saving again.") : _("ACL policy loaded."), i ? "#c60" : "#1a7f37");
        }
    }).catch((i)=>{
        t === e.loadGeneration && (tailnets_u(e, a), tailnets_r(e, i instanceof Error ? i.message : _("Unable to load ACL policy."), "#cf222e"));
    }).finally(()=>{
        t === e.loadGeneration && tailnets_s(e, !1);
    });
}
const main = tailnets_o.extend({
    load: ()=>callTailnets().catch(()=>({
                instances: []
            })),
    render (n) {
        let t = jsx("select", {
            class: "cbi-input-select",
            style: "min-width: 20em;"
        }), o = jsx("div", {}), p = jsx("textarea", {
            class: "cbi-input-text",
            rows: 24,
            spellcheck: !1,
            style: "box-sizing: border-box; font-family: monospace; resize: vertical; width: 100%;"
        }), b = jsx("div", {
            style: "display: none; height: 36em;"
        }), f = jsx("select", {
            class: "cbi-input-select"
        }), y = jsx("button", {
            class: "cbi-button cbi-button-action",
            type: "button",
            children: _("Enable advanced editor")
        }), m = jsxs("div", {
            class: "cbi-value",
            children: [
                jsx("label", {
                    class: "cbi-value-title",
                    children: _("Advanced editor source")
                }),
                jsxs("div", {
                    class: "cbi-value-field",
                    children: [
                        f,
                        " ",
                        y
                    ]
                })
            ]
        }), g = jsx("div", {
            style: "min-height: 1.2em; margin-top: 0.75em;"
        }), E = jsx("button", {
            class: "cbi-button cbi-button-apply",
            type: "button",
            children: _("Validate")
        }), A = jsx("button", {
            class: "cbi-button cbi-button-save",
            type: "button",
            children: _("Save")
        }), C = (n.instances || []).filter((e)=>e.configured && e.name), S = {
            selectEl: t,
            metadataEl: o,
            policyEl: p,
            editorEl: b,
            editorSettingsEl: m,
            editorSourceEl: f,
            enableEditorEl: y,
            messageEl: g,
            validateEl: E,
            saveEl: A,
            tailnets: C,
            instance: "",
            etag: "",
            loadGeneration: 0
        };
        return t.replaceChildren(jsx("option", {
            value: "",
            children: _("Select an API instance")
        }), ...C.map((i)=>jsx("option", {
                value: i.name || "",
                children: i.label || i.name
            }))), f.replaceChildren(jsx("option", {
            value: "auto",
            children: _("Automatic (test all CDNs and use the fastest)")
        }), jsx("option", {
            value: "esm",
            children: "esm.sh"
        }), jsx("option", {
            value: "jsdelivr",
            children: "jsDelivr"
        }), jsx("option", {
            value: "fastly",
            children: "jsDelivr (Fastly)"
        }), jsx("option", {
            value: "gcore",
            children: "jsDelivr (Gcore)"
        }), jsx("option", {
            value: "unpkg",
            children: "unpkg"
        })), v(S), t.onchange = ()=>{
            S.loadGeneration++, S.instance = t.value, S.etag = "", tailnets_u(S, ""), v(S), S.instance ? tailnets_h(S) : tailnets_r(S, "");
        }, E.onclick = ()=>{
            let e;
            return e = tailnets_d(S), void (!S.instance ? tailnets_r(S, _("Select an API instance first."), "#cf222e") : !e.trim() ? tailnets_r(S, _("ACL policy is required."), "#cf222e") : (tailnets_s(S, !0), tailnets_r(S, _("Validating ACL policy...")), callValidateTailnetACL(S.instance, e).then((e)=>{
                if (null == e ? void 0 : e.error) throw Error(e.error);
                tailnets_r(S, _("ACL policy is valid."), "#1a7f37");
            }).catch((e)=>{
                tailnets_r(S, e instanceof Error ? e.message : _("ACL policy validation failed."), "#cf222e");
            }).finally(()=>{
                tailnets_s(S, !1);
            })));
        }, A.onclick = ()=>{
            let e;
            return e = tailnets_d(S), void (!S.instance ? tailnets_r(S, _("Select an API instance first."), "#cf222e") : !e.trim() || !S.etag ? tailnets_r(S, _("Load an ACL policy before saving."), "#cf222e") : (tailnets_s(S, !0), tailnets_r(S, _("Saving ACL policy...")), callSetTailnetACL(S.instance, e, S.etag).then((e)=>{
                if (null == e ? void 0 : e.conflict) return tailnets_h(S, !0);
                if (null == e ? void 0 : e.error) throw Error(e.error);
                return tailnets_h(S);
            }).catch((e)=>{
                tailnets_r(S, e instanceof Error ? e.message : _("Unable to save ACL policy."), "#cf222e");
            }).finally(()=>{
                tailnets_s(S, !1);
            })));
        }, y.onclick = ()=>{
            let e;
            return e = S.editorSourceEl.value, void (S.editorSourceEl.disabled = !0, S.enableEditorEl.disabled = !0, tailnets_r(S, _("Loading advanced editor...")), createMonacoTextEditor(S.editorEl, ()=>S.policyEl.value, (e)=>{
                S.policyEl.value = e;
            }, e).then((e)=>{
                S.editorEl.isConnected ? (S.policyEditor = e, S.policyEl.style.display = "none", S.editorEl.style.display = "block", S.editorSettingsEl.style.display = "none", tailnets_r(S, "")) : e.dispose();
            }).catch(()=>{
                S.editorSourceEl.disabled = !1, S.enableEditorEl.disabled = !1, tailnets_r(S, _("Advanced editor could not be loaded; using the plain text editor."), "#c60");
            }));
        }, jsxs("div", {
            children: [
                jsx("h2", {
                    children: _("Tailnet ACL Management")
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("p", {
                            children: _("Edit the raw ACL policy for one configured Tailscale API instance. Saving validates the policy and uses the loaded ETag to prevent overwriting another administrator's changes.")
                        }),
                        jsxs("div", {
                            class: "cbi-value",
                            children: [
                                jsx("label", {
                                    class: "cbi-value-title",
                                    children: _("API Instance")
                                }),
                                jsx("div", {
                                    class: "cbi-value-field",
                                    children: t
                                })
                            ]
                        }),
                        o
                    ]
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("h3", {
                            children: _("ACL Policy")
                        }),
                        m,
                        p,
                        b,
                        jsxs("div", {
                            style: "margin-top: 0.75em;",
                            children: [
                                E,
                                " ",
                                A
                            ]
                        }),
                        g
                    ]
                })
            ]
        });
    },
    handleSave: null,
    handleSaveApply: null,
    handleReset: null
});


return main;