'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require poll';

// WARN: generated by rsbuild - do not edit


// UNUSED EXPORTS: main

;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = null === n || "object" != typeof n || Array.isArray(n) ? {} : n, { children: l } = s, i = _object_without_properties(s, [
        "children"
    ]), f = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o instanceof Node ? o : String(o)));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...f), e;
    }
    if ("function" == typeof o) {
        let r = Reflect.apply(o, void 0, [
            _object_spread_props(_object_spread({}, i), {
                children: f
            })
        ]);
        if (!(r instanceof Node)) throw TypeError("JSX components must return a DOM Node");
        return r;
    }
    if ("string" != typeof o) throw TypeError("JSX element types must be tag names or component functions");
    let p = {}, c = _object_spread({}, i);
    for (let [e, t] of Object.entries(c))e.startsWith("on") && "function" == typeof t ? (p[e] = t, delete c[e]) : "boolean" == typeof t && (t ? c[e] = e : delete c[e]);
    let a = Object.keys(c).length > 0 ? f.length > 1 ? E(o, c, f) : E(o, c, f[0]) : f.length > 1 ? E(o, {}, f) : E(o, {}, f[0]);
    for (let [e, t] of Object.entries(p)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./src/shared/tailnets.ts
let tailnets_e = L.rpc;
const callTailnets = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "get_tailnets",
    reject: !0
});
const callTailnetACL = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "get_tailnet_acl",
    params: [
        "instance"
    ],
    reject: !0
});
const callValidateTailnetACL = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "validate_tailnet_acl",
    params: [
        "instance",
        "hujson"
    ],
    reject: !0
});
const callSetTailnetACL = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "set_tailnet_acl",
    params: [
        "instance",
        "hujson",
        "etag"
    ],
    reject: !0
});

;// CONCATENATED MODULE: ./src/shared/monaco.ts
let monaco_e, monaco_t, monaco_o;


let monaco_a = "0.56.0", monaco_s = "https://esm.sh/monaco-editor@".concat(monaco_a, "?bundle"), monaco_c = "https://esm.sh/monaco-editor@".concat(monaco_a, "/esm/vs/editor/editor.worker?worker"), monaco_l = "https://esm.sh/monaco-editor@".concat(monaco_a, "/esm/vs/language/json/json.worker?worker"), monaco_i = "".concat("https://cdn.jsdelivr.net/npm/monaco-editor@".concat(monaco_a), "/min/vs/editor/editor.main.css"), d = "https://raw.githubusercontent.com/joneskoo/tailscale/claude/tailscale-acl-json-schema-v2/acl-schema.json";
function monaco_m(e) {
    return Function("url", "return import(url);")(e);
}
async function createMonacoTextEditor(a, u, h) {
    let p = await function() {
        if (monaco_e) return monaco_e;
        let a = Promise.all([
            monaco_m(monaco_s),
            monaco_m(monaco_c),
            monaco_m(monaco_l),
            (monaco_t || (monaco_t = new Promise((e, t)=>{
                let o = document.createElement("link");
                o.rel = "stylesheet", o.href = monaco_i, o.onload = ()=>e(), o.onerror = ()=>t(Error("Unable to load Monaco stylesheet.")), document.head.appendChild(o);
            })).catch(()=>{
                monaco_t = void 0;
            }), monaco_t),
            monaco_o || (monaco_o = fetch(d).then((e)=>{
                if (!e.ok) throw Error("Unable to load the Tailscale ACL schema.");
                return e.json();
            }).catch(()=>void 0))
        ]).then((e)=>{
            let t, o, [a, s, c, , l] = e;
            return o = (t = globalThis).MonacoEnvironment, t.MonacoEnvironment = _object_spread_props(_object_spread({}, o), {
                getWorker: (e, t)=>(null == o ? void 0 : o.getWorker) ? o.getWorker(e, t) : ("json" === t ? c : s).default()
            }), a.json.jsonDefaults.setDiagnosticsOptions({
                allowComments: !0,
                enableSchemaRequest: !1,
                schemas: l ? [
                    {
                        fileMatch: [
                            "*"
                        ],
                        schema: l,
                        uri: d
                    }
                ] : [],
                trailingCommas: "ignore",
                validate: !0
            }), a;
        });
        return monaco_e = a, a.catch(()=>{
            monaco_e === a && (monaco_e = void 0);
        }), a;
    }(), f = p.editor.createModel(u(), "json");
    p.editor.setTheme(!function() {
        for (let e of [
            document.body,
            document.documentElement
        ]){
            let t = function(e) {
                var t;
                let o = null == (t = getComputedStyle(e).backgroundColor.match(/\d+/g)) ? void 0 : t.map(Number);
                if (o && !(o.length < 3) && 0 !== o[3]) return 0.299 * o[0] + 0.587 * o[1] + 0.114 * o[2];
            }(e);
            if (void 0 !== t) return t < 128;
        }
        return matchMedia("(prefers-color-scheme: dark)").matches;
    }() ? "vs" : "vs-dark");
    let g = p.editor.create(a, {
        automaticLayout: !0,
        minimap: {
            enabled: !1
        },
        model: f,
        scrollBeyondLastLine: !1,
        tabSize: 2,
        wordWrap: "on"
    }), v = f.onDidChangeContent(()=>h(f.getValue()));
    return {
        getValue: ()=>f.getValue(),
        setValue (e) {
            f.setValue(e);
        },
        dispose () {
            v.dispose(), g.dispose(), f.dispose();
        }
    };
}

;// CONCATENATED MODULE: ./src/views/tailnets.tsx



let tailnets_o = L.view;
function tailnets_r(e, i) {
    let l = arguments.length > 2 && void 0 !== arguments[2] ? arguments[2] : "";
    e.messageEl.style.color = l, e.messageEl.textContent = i;
}
function tailnets_s(e, i) {
    e.loadEl.disabled = i, e.validateEl.disabled = i, e.saveEl.disabled = i;
}
function tailnets_d(e) {
    var i, l;
    return null != (i = null == (l = e.policyEditor) ? void 0 : l.getValue()) ? i : e.policyEl.value;
}
function tailnets_u(e, i) {
    var l;
    e.policyEl.value = i, null == (l = e.policyEditor) || l.setValue(i);
}
function tailnets_h(l) {
    let n = l.tailnets.find((e)=>e.name === l.instance);
    n ? l.metadataEl.replaceChildren(jsxs("div", {
        class: "cbi-value",
        children: [
            jsx("label", {
                class: "cbi-value-title",
                children: _("Tailnet")
            }),
            jsx("div", {
                class: "cbi-value-field",
                children: n.tailnet || "-"
            })
        ]
    }), jsxs("div", {
        class: "cbi-value",
        children: [
            jsx("label", {
                class: "cbi-value-title",
                children: _("Instance")
            }),
            jsx("div", {
                class: "cbi-value-field",
                style: "font-family: monospace;",
                children: n.name || "-"
            })
        ]
    })) : l.metadataEl.replaceChildren(jsx("p", {
        children: _("Select a configured API instance to manage its ACL policy.")
    }));
}
function tailnets_v(e) {
    let i = arguments.length > 1 && void 0 !== arguments[1] && arguments[1];
    if (!e.instance) return tailnets_r(e, _("Select an API instance first."), "#cf222e"), Promise.resolve();
    let l = tailnets_d(e);
    return tailnets_s(e, !0), tailnets_r(e, _("Loading ACL policy...")), callTailnetACL(e.instance).then((l)=>{
        if (null == l ? void 0 : l.error) throw Error(l.error);
        e.etag = (null == l ? void 0 : l.etag) || "", i || tailnets_u(e, (null == l ? void 0 : l.hujson) || ""), tailnets_r(e, i ? _("The server policy changed. Your draft was retained; review it before saving again.") : _("ACL policy loaded."), i ? "#c60" : "#1a7f37");
    }).catch((i)=>{
        tailnets_u(e, l), tailnets_r(e, i instanceof Error ? i.message : _("Unable to load ACL policy."), "#cf222e");
    }).finally(()=>{
        tailnets_s(e, !1);
    });
}
const main = tailnets_o.extend({
    load: ()=>callTailnets().catch(()=>({
                instances: []
            })),
    render (n) {
        let t = jsx("select", {
            class: "cbi-input-select",
            style: "min-width: 20em;"
        }), o = jsx("div", {}), p = jsx("textarea", {
            class: "cbi-input-text",
            rows: 24,
            spellcheck: !1,
            style: "box-sizing: border-box; font-family: monospace; resize: vertical; width: 100%;"
        }), f = jsx("div", {
            style: "display: none; height: 36em;"
        }), b = jsx("div", {
            style: "min-height: 1.2em; margin-top: 0.75em;"
        }), y = jsx("button", {
            class: "cbi-button cbi-button-action",
            type: "button",
            children: _("Load")
        }), m = jsx("button", {
            class: "cbi-button cbi-button-apply",
            type: "button",
            children: _("Validate")
        }), g = jsx("button", {
            class: "cbi-button cbi-button-save",
            type: "button",
            children: _("Save")
        }), A = (n.instances || []).filter((e)=>e.configured && e.name), C = {
            selectEl: t,
            metadataEl: o,
            policyEl: p,
            messageEl: b,
            loadEl: y,
            validateEl: m,
            saveEl: g,
            tailnets: A,
            instance: "",
            etag: ""
        };
        return t.replaceChildren(jsx("option", {
            value: "",
            children: _("Select an API instance")
        }), ...A.map((i)=>jsx("option", {
                value: i.name || "",
                children: i.label || i.name
            }))), tailnets_h(C), t.onchange = ()=>{
            C.instance = t.value, C.etag = "", tailnets_u(C, ""), tailnets_h(C), tailnets_r(C, C.instance ? _("Load the ACL policy to begin editing.") : "");
        }, y.onclick = ()=>{
            tailnets_v(C);
        }, m.onclick = ()=>{
            let e;
            return e = tailnets_d(C), void (!C.instance ? tailnets_r(C, _("Select an API instance first."), "#cf222e") : !e.trim() ? tailnets_r(C, _("ACL policy is required."), "#cf222e") : (tailnets_s(C, !0), tailnets_r(C, _("Validating ACL policy...")), callValidateTailnetACL(C.instance, e).then((e)=>{
                if (null == e ? void 0 : e.error) throw Error(e.error);
                tailnets_r(C, _("ACL policy is valid."), "#1a7f37");
            }).catch((e)=>{
                tailnets_r(C, e instanceof Error ? e.message : _("ACL policy validation failed."), "#cf222e");
            }).finally(()=>{
                tailnets_s(C, !1);
            })));
        }, g.onclick = ()=>{
            let e;
            return e = tailnets_d(C), void (!C.instance ? tailnets_r(C, _("Select an API instance first."), "#cf222e") : !e.trim() || !C.etag ? tailnets_r(C, _("Load an ACL policy before saving."), "#cf222e") : (tailnets_s(C, !0), tailnets_r(C, _("Saving ACL policy...")), callSetTailnetACL(C.instance, e, C.etag).then((e)=>{
                if (null == e ? void 0 : e.conflict) return tailnets_v(C, !0);
                if (null == e ? void 0 : e.error) throw Error(e.error);
                return tailnets_v(C);
            }).catch((e)=>{
                tailnets_r(C, e instanceof Error ? e.message : _("Unable to save ACL policy."), "#cf222e");
            }).finally(()=>{
                tailnets_s(C, !1);
            })));
        }, createMonacoTextEditor(f, ()=>p.value, (e)=>{
            p.value = e;
        }).then((e)=>{
            f.isConnected ? (C.policyEditor = e, p.style.display = "none", f.style.display = "block") : e.dispose();
        }).catch(()=>{
            tailnets_r(C, _("Advanced editor could not be loaded; using the plain text editor."), "#c60");
        }), jsxs("div", {
            children: [
                jsx("h2", {
                    children: _("Tailnet ACL Management")
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("p", {
                            children: _("Edit the raw HuJSON ACL policy for one configured Tailscale API instance. Saving validates the policy and uses the loaded ETag to prevent overwriting another administrator's changes.")
                        }),
                        jsxs("div", {
                            class: "cbi-value",
                            children: [
                                jsx("label", {
                                    class: "cbi-value-title",
                                    children: _("API Instance")
                                }),
                                jsx("div", {
                                    class: "cbi-value-field",
                                    children: t
                                })
                            ]
                        }),
                        o
                    ]
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("h3", {
                            children: _("ACL Policy (HuJSON)")
                        }),
                        p,
                        f,
                        jsxs("div", {
                            style: "margin-top: 0.75em;",
                            children: [
                                y,
                                " ",
                                m,
                                " ",
                                g
                            ]
                        }),
                        b
                    ]
                })
            ]
        });
    },
    handleSave: null,
    handleSaveApply: null,
    handleReset: null
});


return main;