'use strict';
'require view';
'require form';
'require rpc';
'require ui';
'require uci';
'require poll';

// WARN: generated by rsbuild - do not edit


// UNUSED EXPORTS: main

;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ./node_modules/.pnpm/@swc+helpers@0.5.21/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = null === n || "object" != typeof n || Array.isArray(n) ? {} : n, { children: l } = s, i = _object_without_properties(s, [
        "children"
    ]), f = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o instanceof Node ? o : String(o)));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...f), e;
    }
    if ("function" == typeof o) {
        let r = Reflect.apply(o, void 0, [
            _object_spread_props(_object_spread({}, i), {
                children: f
            })
        ]);
        if (!(r instanceof Node)) throw TypeError("JSX components must return a DOM Node");
        return r;
    }
    if ("string" != typeof o) throw TypeError("JSX element types must be tag names or component functions");
    let p = {}, c = _object_spread({}, i);
    for (let [e, t] of Object.entries(c))e.startsWith("on") && "function" == typeof t ? (p[e] = t, delete c[e]) : "boolean" == typeof t && (t ? c[e] = e : delete c[e]);
    let a = Object.keys(c).length > 0 ? f.length > 1 ? E(o, c, f) : E(o, c, f[0]) : f.length > 1 ? E(o, {}, f) : E(o, {}, f[0]);
    for (let [e, t] of Object.entries(p)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ./node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./src/shared/tailnets.ts
let tailnets_e = L.rpc;
const callTailnets = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "get_tailnets",
    reject: !0
});
const callTailnetACL = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "get_tailnet_acl",
    params: [
        "instance"
    ],
    reject: !0
});
const callSetDeviceIPv4 = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "set_device_ipv4",
    params: [
        "instance",
        "device_id",
        "ipv4"
    ],
    reject: !0
});
const callValidateTailnetACL = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "validate_tailnet_acl",
    params: [
        "instance",
        "hujson"
    ],
    reject: !0
});
const callSetTailnetACL = tailnets_e.declare({
    object: "luci.tailscale-derp",
    method: "set_tailnet_acl",
    params: [
        "instance",
        "hujson",
        "etag"
    ],
    reject: !0
});

;// CONCATENATED MODULE: ./src/views/tailnets.tsx


let tailnets_c = L.view;
function tailnets_o(e, i) {
    let l = arguments.length > 2 && void 0 !== arguments[2] ? arguments[2] : "";
    e.messageEl.style.color = l, e.messageEl.textContent = i;
}
function tailnets_r(e, i) {
    e.loadEl.disabled = i, e.validateEl.disabled = i, e.saveEl.disabled = i;
}
function tailnets_s(l) {
    let n = l.tailnets.find((e)=>e.name === l.instance);
    n ? l.metadataEl.replaceChildren(jsxs("div", {
        class: "cbi-value",
        children: [
            jsx("label", {
                class: "cbi-value-title",
                children: _("Tailnet")
            }),
            jsx("div", {
                class: "cbi-value-field",
                children: n.tailnet || "-"
            })
        ]
    }), jsxs("div", {
        class: "cbi-value",
        children: [
            jsx("label", {
                class: "cbi-value-title",
                children: _("Instance")
            }),
            jsx("div", {
                class: "cbi-value-field",
                style: "font-family: monospace;",
                children: n.name || "-"
            })
        ]
    })) : l.metadataEl.replaceChildren(jsx("p", {
        children: _("Select a configured API instance to manage its ACL policy.")
    }));
}
function d(e) {
    let i = arguments.length > 1 && void 0 !== arguments[1] && arguments[1];
    if (!e.instance) return tailnets_o(e, _("Select an API instance first."), "#cf222e"), Promise.resolve();
    let l = e.policyEl.value;
    return tailnets_r(e, !0), tailnets_o(e, _("Loading ACL policy...")), callTailnetACL(e.instance).then((l)=>{
        if (null == l ? void 0 : l.error) throw Error(l.error);
        e.etag = (null == l ? void 0 : l.etag) || "", i || (e.policyEl.value = (null == l ? void 0 : l.hujson) || ""), tailnets_o(e, i ? _("The server policy changed. Your draft was retained; review it before saving again.") : _("ACL policy loaded."), i ? "#c60" : "#1a7f37");
    }).catch((i)=>{
        e.policyEl.value = l, tailnets_o(e, i instanceof Error ? i.message : _("Unable to load ACL policy."), "#cf222e");
    }).finally(()=>{
        tailnets_r(e, !1);
    });
}
const main = tailnets_c.extend({
    load: ()=>callTailnets().catch(()=>({
                instances: []
            })),
    render (n) {
        let a = jsx("select", {
            class: "cbi-input-select",
            style: "min-width: 20em;"
        }), c = jsx("div", {}), u = jsx("textarea", {
            class: "cbi-input-text",
            rows: 24,
            spellcheck: !1,
            style: "box-sizing: border-box; font-family: monospace; resize: vertical; width: 100%;"
        }), v = jsx("div", {
            style: "min-height: 1.2em; margin-top: 0.75em;"
        }), h = jsx("button", {
            class: "cbi-button cbi-button-action",
            type: "button",
            children: _("Load")
        }), f = jsx("button", {
            class: "cbi-button cbi-button-apply",
            type: "button",
            children: _("Validate")
        }), p = jsx("button", {
            class: "cbi-button cbi-button-save",
            type: "button",
            children: _("Save")
        }), b = (n.instances || []).filter((e)=>e.configured && e.name), y = {
            selectEl: a,
            metadataEl: c,
            policyEl: u,
            messageEl: v,
            loadEl: h,
            validateEl: f,
            saveEl: p,
            tailnets: b,
            instance: "",
            etag: ""
        };
        return a.replaceChildren(jsx("option", {
            value: "",
            children: _("Select an API instance")
        }), ...b.map((i)=>jsx("option", {
                value: i.name || "",
                children: i.label || i.name
            }))), tailnets_s(y), a.onchange = ()=>{
            y.instance = a.value, y.etag = "", y.policyEl.value = "", tailnets_s(y), tailnets_o(y, y.instance ? _("Load the ACL policy to begin editing.") : "");
        }, h.onclick = ()=>{
            d(y);
        }, f.onclick = ()=>{
            let e;
            return e = y.policyEl.value, void (!y.instance ? tailnets_o(y, _("Select an API instance first."), "#cf222e") : !e.trim() ? tailnets_o(y, _("ACL policy is required."), "#cf222e") : (tailnets_r(y, !0), tailnets_o(y, _("Validating ACL policy...")), callValidateTailnetACL(y.instance, e).then((e)=>{
                if (null == e ? void 0 : e.error) throw Error(e.error);
                tailnets_o(y, _("ACL policy is valid."), "#1a7f37");
            }).catch((e)=>{
                tailnets_o(y, e instanceof Error ? e.message : _("ACL policy validation failed."), "#cf222e");
            }).finally(()=>{
                tailnets_r(y, !1);
            })));
        }, p.onclick = ()=>{
            let e;
            return e = y.policyEl.value, void (!y.instance ? tailnets_o(y, _("Select an API instance first."), "#cf222e") : !e.trim() || !y.etag ? tailnets_o(y, _("Load an ACL policy before saving."), "#cf222e") : (tailnets_r(y, !0), tailnets_o(y, _("Saving ACL policy...")), callSetTailnetACL(y.instance, e, y.etag).then((e)=>{
                if (null == e ? void 0 : e.conflict) return d(y, !0);
                if (null == e ? void 0 : e.error) throw Error(e.error);
                return d(y);
            }).catch((e)=>{
                tailnets_o(y, e instanceof Error ? e.message : _("Unable to save ACL policy."), "#cf222e");
            }).finally(()=>{
                tailnets_r(y, !1);
            })));
        }, jsxs("div", {
            children: [
                jsx("h2", {
                    children: _("Tailnet ACL Management")
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("p", {
                            children: _("Edit the raw HuJSON ACL policy for one configured Tailscale API instance. Saving validates the policy and uses the loaded ETag to prevent overwriting another administrator's changes.")
                        }),
                        jsxs("div", {
                            class: "cbi-value",
                            children: [
                                jsx("label", {
                                    class: "cbi-value-title",
                                    children: _("API Instance")
                                }),
                                jsx("div", {
                                    class: "cbi-value-field",
                                    children: a
                                })
                            ]
                        }),
                        c
                    ]
                }),
                jsxs("div", {
                    class: "cbi-section",
                    children: [
                        jsx("h3", {
                            children: _("ACL Policy (HuJSON)")
                        }),
                        u,
                        jsxs("div", {
                            style: "margin-top: 0.75em;",
                            children: [
                                h,
                                " ",
                                f,
                                " ",
                                p
                            ]
                        }),
                        v
                    ]
                })
            ]
        });
    },
    handleSave: null,
    handleSaveApply: null,
    handleReset: null
});


return main;